# Vision Model Comparison

Compare synthetic baseline behavior across standard vision backbones and a CLIP image encoder.

In [1]:
# This setup cell has no meaningful table output.
# It imports the runner and data tools used by the later cells.

from pathlib import Path
import json
import pandas as pd

from vision.model_comparison import DEFAULT_MODEL_NAMES
from vision.run_model_comparison import run_model_comparison

In [2]:
# This cell prints the model list that will be compared.
# The output is just the benchmark configuration: which backbones, device, image size,
# and random seed are being used for the synthetic comparison.

MODEL_NAMES = list(DEFAULT_MODEL_NAMES)
DEVICE = "cpu"
BATCH_SIZE = 16
IMAGE_SIZE = 224
SEED = 0
OUTPUT_DIR = Path("results/vision/model_comparison")

MODEL_NAMES

['vit_base_patch16_224', 'vit_base_patch16_clip_224.openai', 'convnext_tiny']

In [3]:
# This cell runs the full synthetic model-comparison benchmark.
# The returned summary tells you whether all sanity checks passed, which rows gave the best
# identification and generalization, and whether any tradeoff candidates were found.
# Main finding in this notebook: no model produced the desired tradeoff curve.

summary = run_model_comparison(
    model_names=MODEL_NAMES,
    device=DEVICE,
    batch_size=BATCH_SIZE,
    image_size=IMAGE_SIZE,
    seed=SEED,
    output_dir=OUTPUT_DIR,
)
summary

[1/90] {'model_name': 'vit_base_patch16_224', 'pooling': 'cls', 'task_mode': 'mixed_color_position', 'n_per_color': 12, 'n_stored_per_color': 2, 'square_size': 56, 'ident_noise_std': 0.0, 'ident_max_shift': 0, 'color_only_jitter_std': 0.0}

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

[2/90] {'model_name': 'vit_base_patch16_224', 'pooling': 'cls', 'task_mode': 'mixed_color_position', 'n_per_color': 12, 'n_stored_per_color': 4, 'square_size': 56, 'ident_noise_std': 0.0, 'ident_max_shift': 0, 'color_only_jitter_std': 0.0}
[3/90] {'model_name': 'vit_base_patch16_224', 'pooling': 'cls', 'task_mode': 'mixed_color_position', 'n_per_color': 12, 'n_stored_per_color': 6, 'square_size': 56, 'ident_noise_std': 0.0, 'ident_max_shift': 0, 'color_only_jitter_std': 0.0}
[4/90] {'model_name': 'vit_base_patch16_224', 'pooling': 'cls', 'task_mode': 'mixed_color_position', 'n_per_color': 12, 'n_stored_per_color': 2, 'square_size': 56, 'ident_noise_std': 5.0, 'ident_max_shift': 2, 'color_only_jitter_std': 0.0}
[5/90] {'model_name': 'vit_base_patch16_224', 'pooling': 'cls', 'task_mode': 'mixed_color_position', 'n_per_color': 12, 'n_stored_per_color': 4, 'square_size': 56, 'ident_noise_std': 5.0, 'ident_max_shift': 2, 'color_only_jitter_std': 0.0}
[6/90] {'model_name': 'vit_base_patch16_224', 'pooling': 'cls', 'task_mode': 'mixed_color_position', 'n_per_color': 12, 'n_stored_per_color': 6, 'square_size': 56, 'ident_noise_std': 5.0, 'ident_max_shift': 2, 'color_only_jitter_std': 0.0}
[7/90] {'model_name': 'vit_base_patch16_224', 'pooling': 'cls', 'task_mode': 'color_only', 'n_per_color': 12, 'n_stored_per_color': 2, 'square_size': 56, 'ident_noise_std': 0.0, 'ident_max_shift': 0, 'color_only_jitter_std': 8.0}
[8/90] {'model_name': 'vit_base_patch16_224', 'pooling': 'cls', 'task_mode': 'color_only', 'n_per_color': 12, 'n_stored_per_color': 4, 'square_size': 56, 'ident_noise_std': 0.0, 'ident_max_shift': 0, 'color_only_jitter_std': 8.0}
[9/90] {'model_name': 'vit_base_patch16_224', 'pooling': 'cls', 'task_mode': 'color_only', 'n_per_color': 12, 'n_stored_per_color': 6, 'square_size': 56, 'ident_noise_std': 0.0, 'ident_max_shift': 0, 'color_only_jitter_std': 8.0}
[10/90] {'model_name': 'vit_base_patch16_224', 'pooling': 'cls', 'task_mode': 'color_only', 'n_per_color': 12, 'n_stored_per_color': 2, 'square_size': 56, 'ident_noise_std': 5.0, 'ident_max_shift': 2, 'color_only_jitter_std': 8.0}
[11/90] {'model_name': 'vit_base_patch16_224', 'pooling': 'cls', 'task_mode': 'color_only', 'n_per_color': 12, 'n_stored_per_color': 4, 'square_size': 56, 'ident_noise_std': 5.0, 'ident_max_shift': 2, 'color_only_jitter_std': 8.0}
[12/90] {'model_name': 'vit_base_patch16_224', 'pooling': 'cls', 'task_mode': 'color_only', 'n_per_color': 12, 'n_stored_per_color': 6, 'square_size': 56, 'ident_noise_std': 5.0, 'ident_max_shift': 2, 'color_only_jitter_std': 8.0}
[13/90] {'model_name': 'vit_base_patch16_224', 'pooling': 'cls', 'task_mode': 'position_only', 'n_per_color': 12, 'n_stored_per_color': 2, 'square_size': 56, 'ident_noise_std': 0.0, 'ident_max_shift': 0, 'color_only_jitter_std': 0.0}
[14/90] {'model_name': 'vit_base_patch16_224', 'pooling': 'cls', 'task_mode': 'position_only', 'n_per_color': 12, 'n_stored_per_color': 4, 'square_size': 56, 'ident_noise_std': 0.0, 'ident_max_shift': 0, 'color_only_jitter_std': 0.0}
[15/90] {'model_name': 'vit_base_patch16_224', 'pooling': 'cls', 'task_mode': 'position_only', 'n_per_color': 12, 'n_stored_per_color': 6, 'square_size': 56, 'ident_noise_std': 0.0, 'ident_max_shift': 0, 'color_only_jitter_std': 0.0}
[16/90] {'model_name': 'vit_base_patch16_224', 'pooling': 'cls', 'task_mode': 'position_only', 'n_per_color': 12, 'n_stored_per_color': 2, 'square_size': 56, 'ident_noise_std': 5.0, 'ident_max_shift': 2, 'color_only_jitter_std': 0.0}
[17/90] {'model_name': 'vit_base_patch16_224', 'pooling': 'cls', 'task_mode': 'position_only', 'n_per_color': 12, 'n_stored_per_color': 4, 'square_size': 56, 'ident_noise_std': 5.0, 'ident_max_shift': 2, 'color_only_jitter_std': 0.0}
[18/90] {'model_name': 'vit_base_patch16_224', 'pooling': 'cls', 'task_mode': 'position_only', 'n_per_color': 12, 'n_stored_per_color': 6, 'square_size': 56, 'ident_noise_std': 5.0, 'ident_max_shift': 2, 'color_only_jitter_std': 0.0}
[19/90] {'model_name': 'vit_base_patch16_224', 'pooling': 'mean_tokens', 'task_mode': 'mixed_color_position', 'n_per_color': 12, 'n_stored_per_color': 2, 'square_size': 56, 'ident_noise_std': 0.0, 'ident_max_shift': 0, 'color_only_jitter_std': 0.0}
[20/90] {'model_name': 'vit_base_patch16_224', 'pooling': 'mean_tokens', 'task_mode': 'mixed_color_position', 'n_per_color': 12, 'n_stored_per_color': 4, 'square_size': 56, 'ident_noise_std': 0.0, 'ident_max_shift': 0, 'color_only_jitter_std': 0.0}
[21/90] {'model_name': 'vit_base_patch16_224', 'pooling': 'mean_tokens', 'task_mode': 'mixed_color_position', 'n_per_color': 12, 'n_stored_per_color': 6, 'square_size': 56, 'ident_noise_std': 0.0, 'ident_max_shift': 0, 'color_only_jitter_std': 0.0}
[22/90] {'model_name': 'vit_base_patch16_224', 'pooling': 'mean_tokens', 'task_mode': 'mixed_color_position', 'n_per_color': 12, 'n_stored_per_color': 2, 'square_size': 56, 'ident_noise_std': 5.0, 'ident_max_shift': 2, 'color_only_jitter_std': 0.0}
[23/90] {'model_name': 'vit_base_patch16_224', 'pooling': 'mean_tokens', 'task_mode': 'mixed_color_position', 'n_per_color': 12, 'n_stored_per_color': 4, 'square_size': 56, 'ident_noise_std': 5.0, 'ident_max_shift': 2, 'color_only_jitter_std': 0.0}
[24/90] {'model_name': 'vit_base_patch16_224', 'pooling': 'mean_tokens', 'task_mode': 'mixed_color_position', 'n_per_color': 12, 'n_stored_per_color': 6, 'square_size': 56, 'ident_noise_std': 5.0, 'ident_max_shift': 2, 'color_only_jitter_std': 0.0}
[25/90] {'model_name': 'vit_base_patch16_224', 'pooling': 'mean_tokens', 'task_mode': 'color_only', 'n_per_color': 12, 'n_stored_per_color': 2, 'square_size': 56, 'ident_noise_std': 0.0, 'ident_max_shift': 0, 'color_only_jitter_std': 8.0}
[26/90] {'model_name': 'vit_base_patch16_224', 'pooling': 'mean_tokens', 'task_mode': 'color_only', 'n_per_color': 12, 'n_stored_per_color': 4, 'square_size': 56, 'ident_noise_std': 0.0, 'ident_max_shift': 0, 'color_only_jitter_std': 8.0}
[27/90] {'model_name': 'vit_base_patch16_224', 'pooling': 'mean_tokens', 'task_mode': 'color_only', 'n_per_color': 12, 'n_stored_per_color': 6, 'square_size': 56, 'ident_noise_std': 0.0, 'ident_max_shift': 0, 'color_only_jitter_std': 8.0}
[28/90] {'model_name': 'vit_base_patch16_224', 'pooling': 'mean_tokens', 'task_mode': 'color_only', 'n_per_color': 12, 'n_stored_per_color': 2, 'square_size': 56, 'ident_noise_std': 5.0, 'ident_max_shift': 2, 'color_only_jitter_std': 8.0}
[29/90] {'model_name': 'vit_base_patch16_224', 'pooling': 'mean_tokens', 'task_mode': 'color_only', 'n_per_color': 12, 'n_stored_per_color': 4, 'square_size': 56, 'ident_noise_std': 5.0, 'ident_max_shift': 2, 'color_only_jitter_std': 8.0}
[30/90] {'model_name': 'vit_base_patch16_224', 'pooling': 'mean_tokens', 'task_mode': 'color_only', 'n_per_color': 12, 'n_stored_per_color': 6, 'square_size': 56, 'ident_noise_std': 5.0, 'ident_max_shift': 2, 'color_only_jitter_std': 8.0}
[31/90] {'model_name': 'vit_base_patch16_224', 'pooling': 'mean_tokens', 'task_mode': 'position_only', 'n_per_color': 12, 'n_stored_per_color': 2, 'square_size': 56, 'ident_noise_std': 0.0, 'ident_max_shift': 0, 'color_only_jitter_std': 0.0}
[32/90] {'model_name': 'vit_base_patch16_224', 'pooling': 'mean_tokens', 'task_mode': 'position_only', 'n_per_color': 12, 'n_stored_per_color': 4, 'square_size': 56, 'ident_noise_std': 0.0, 'ident_max_shift': 0, 'color_only_jitter_std': 0.0}
[33/90] {'model_name': 'vit_base_patch16_224', 'pooling': 'mean_tokens', 'task_mode': 'position_only', 'n_per_color': 12, 'n_stored_per_color': 6, 'square_size': 56, 'ident_noise_std': 0.0, 'ident_max_shift': 0, 'color_only_jitter_std': 0.0}
[34/90] {'model_name': 'vit_base_patch16_224', 'pooling': 'mean_tokens', 'task_mode': 'position_only', 'n_per_color': 12, 'n_stored_per_color': 2, 'square_size': 56, 'ident_noise_std': 5.0, 'ident_max_shift': 2, 'color_only_jitter_std': 0.0}
[35/90] {'model_name': 'vit_base_patch16_224', 'pooling': 'mean_tokens', 'task_mode': 'position_only', 'n_per_color': 12, 'n_stored_per_color': 4, 'square_size': 56, 'ident_noise_std': 5.0, 'ident_max_shift': 2, 'color_only_jitter_std': 0.0}
[36/90] {'model_name': 'vit_base_patch16_224', 'pooling': 'mean_tokens', 'task_mode': 'position_only', 'n_per_color': 12, 'n_stored_per_color': 6, 'square_size': 56, 'ident_noise_std': 5.0, 'ident_max_shift': 2, 'color_only_jitter_std': 0.0}
[37/90] {'model_name': 'vit_base_patch16_clip_224.openai', 'pooling': 'cls', 'task_mode': 'mixed_color_position', 'n_per_color': 12, 'n_stored_per_color': 2, 'square_size': 56, 'ident_noise_std': 0.0, 'ident_max_shift': 0, 'color_only_jitter_std': 0.0}
[38/90] {'model_name': 'vit_base_patch16_clip_224.openai', 'pooling': 'cls', 'task_mode': 'mixed_color_position', 'n_per_color': 12, 'n_stored_per_color': 4, 'square_size': 56, 'ident_noise_std': 0.0, 'ident_max_shift': 0, 'color_only_jitter_std': 0.0}
[39/90] {'model_name': 'vit_base_patch16_clip_224.openai', 'pooling': 'cls', 'task_mode': 'mixed_color_position', 'n_per_color': 12, 'n_stored_per_color': 6, 'square_size': 56, 'ident_noise_std': 0.0, 'ident_max_shift': 0, 'color_only_jitter_std': 0.0}
[40/90] {'model_name': 'vit_base_patch16_clip_224.openai', 'pooling': 'cls', 'task_mode': 'mixed_color_position', 'n_per_color': 12, 'n_stored_per_color': 2, 'square_size': 56, 'ident_noise_std': 5.0, 'ident_max_shift': 2, 'color_only_jitter_std': 0.0}
[41/90] {'model_name': 'vit_base_patch16_clip_224.openai', 'pooling': 'cls', 'task_mode': 'mixed_color_position', 'n_per_color': 12, 'n_stored_per_color': 4, 'square_size': 56, 'ident_noise_std': 5.0, 'ident_max_shift': 2, 'color_only_jitter_std': 0.0}
[42/90] {'model_name': 'vit_base_patch16_clip_224.openai', 'pooling': 'cls', 'task_mode': 'mixed_color_position', 'n_per_color': 12, 'n_stored_per_color': 6, 'square_size': 56, 'ident_noise_std': 5.0, 'ident_max_shift': 2, 'color_only_jitter_std': 0.0}
[43/90] {'model_name': 'vit_base_patch16_clip_224.openai', 'pooling': 'cls', 'task_mode': 'color_only', 'n_per_color': 12, 'n_stored_per_color': 2, 'square_size': 56, 'ident_noise_std': 0.0, 'ident_max_shift': 0, 'color_only_jitter_std': 8.0}
[44/90] {'model_name': 'vit_base_patch16_clip_224.openai', 'pooling': 'cls', 'task_mode': 'color_only', 'n_per_color': 12, 'n_stored_per_color': 4, 'square_size': 56, 'ident_noise_std': 0.0, 'ident_max_shift': 0, 'color_only_jitter_std': 8.0}
[45/90] {'model_name': 'vit_base_patch16_clip_224.openai', 'pooling': 'cls', 'task_mode': 'color_only', 'n_per_color': 12, 'n_stored_per_color': 6, 'square_size': 56, 'ident_noise_std': 0.0, 'ident_max_shift': 0, 'color_only_jitter_std': 8.0}
[46/90] {'model_name': 'vit_base_patch16_clip_224.openai', 'pooling': 'cls', 'task_mode': 'color_only', 'n_per_color': 12, 'n_stored_per_color': 2, 'square_size': 56, 'ident_noise_std': 5.0, 'ident_max_shift': 2, 'color_only_jitter_std': 8.0}
[47/90] {'model_name': 'vit_base_patch16_clip_224.openai', 'pooling': 'cls', 'task_mode': 'color_only', 'n_per_color': 12, 'n_stored_per_color': 4, 'square_size': 56, 'ident_noise_std': 5.0, 'ident_max_shift': 2, 'color_only_jitter_std': 8.0}
[48/90] {'model_name': 'vit_base_patch16_clip_224.openai', 'pooling': 'cls', 'task_mode': 'color_only', 'n_per_color': 12, 'n_stored_per_color': 6, 'square_size': 56, 'ident_noise_std': 5.0, 'ident_max_shift': 2, 'color_only_jitter_std': 8.0}
[49/90] {'model_name': 'vit_base_patch16_clip_224.openai', 'pooling': 'cls', 'task_mode': 'position_only', 'n_per_color': 12, 'n_stored_per_color': 2, 'square_size': 56, 'ident_noise_std': 0.0, 'ident_max_shift': 0, 'color_only_jitter_std': 0.0}
[50/90] {'model_name': 'vit_base_patch16_clip_224.openai', 'pooling': 'cls', 'task_mode': 'position_only', 'n_per_color': 12, 'n_stored_per_color': 4, 'square_size': 56, 'ident_noise_std': 0.0, 'ident_max_shift': 0, 'color_only_jitter_std': 0.0}
[51/90] {'model_name': 'vit_base_patch16_clip_224.openai', 'pooling': 'cls', 'task_mode': 'position_only', 'n_per_color': 12, 'n_stored_per_color': 6, 'square_size': 56, 'ident_noise_std': 0.0, 'ident_max_shift': 0, 'color_only_jitter_std': 0.0}
[52/90] {'model_name': 'vit_base_patch16_clip_224.openai', 'pooling': 'cls', 'task_mode': 'position_only', 'n_per_color': 12, 'n_stored_per_color': 2, 'square_size': 56, 'ident_noise_std': 5.0, 'ident_max_shift': 2, 'color_only_jitter_std': 0.0}
[53/90] {'model_name': 'vit_base_patch16_clip_224.openai', 'pooling': 'cls', 'task_mode': 'position_only', 'n_per_color': 12, 'n_stored_per_color': 4, 'square_size': 56, 'ident_noise_std': 5.0, 'ident_max_shift': 2, 'color_only_jitter_std': 0.0}
[54/90] {'model_name': 'vit_base_patch16_clip_224.openai', 'pooling': 'cls', 'task_mode': 'position_only', 'n_per_color': 12, 'n_stored_per_color': 6, 'square_size': 56, 'ident_noise_std': 5.0, 'ident_max_shift': 2, 'color_only_jitter_std': 0.0}
[55/90] {'model_name': 'vit_base_patch16_clip_224.openai', 'pooling': 'mean_tokens', 'task_mode': 'mixed_color_position', 'n_per_color': 12, 'n_stored_per_color': 2, 'square_size': 56, 'ident_noise_std': 0.0, 'ident_max_shift': 0, 'color_only_jitter_std': 0.0}
[56/90] {'model_name': 'vit_base_patch16_clip_224.openai', 'pooling': 'mean_tokens', 'task_mode': 'mixed_color_position', 'n_per_color': 12, 'n_stored_per_color': 4, 'square_size': 56, 'ident_noise_std': 0.0, 'ident_max_shift': 0, 'color_only_jitter_std': 0.0}
[57/90] {'model_name': 'vit_base_patch16_clip_224.openai', 'pooling': 'mean_tokens', 'task_mode': 'mixed_color_position', 'n_per_color': 12, 'n_stored_per_color': 6, 'square_size': 56, 'ident_noise_std': 0.0, 'ident_max_shift': 0, 'color_only_jitter_std': 0.0}
[58/90] {'model_name': 'vit_base_patch16_clip_224.openai', 'pooling': 'mean_tokens', 'task_mode': 'mixed_color_position', 'n_per_color': 12, 'n_stored_per_color': 2, 'square_size': 56, 'ident_noise_std': 5.0, 'ident_max_shift': 2, 'color_only_jitter_std': 0.0}
[59/90] {'model_name': 'vit_base_patch16_clip_224.openai', 'pooling': 'mean_tokens', 'task_mode': 'mixed_color_position', 'n_per_color': 12, 'n_stored_per_color': 4, 'square_size': 56, 'ident_noise_std': 5.0, 'ident_max_shift': 2, 'color_only_jitter_std': 0.0}
[60/90] {'model_name': 'vit_base_patch16_clip_224.openai', 'pooling': 'mean_tokens', 'task_mode': 'mixed_color_position', 'n_per_color': 12, 'n_stored_per_color': 6, 'square_size': 56, 'ident_noise_std': 5.0, 'ident_max_shift': 2, 'color_only_jitter_std': 0.0}
[61/90] {'model_name': 'vit_base_patch16_clip_224.openai', 'pooling': 'mean_tokens', 'task_mode': 'color_only', 'n_per_color': 12, 'n_stored_per_color': 2, 'square_size': 56, 'ident_noise_std': 0.0, 'ident_max_shift': 0, 'color_only_jitter_std': 8.0}
[62/90] {'model_name': 'vit_base_patch16_clip_224.openai', 'pooling': 'mean_tokens', 'task_mode': 'color_only', 'n_per_color': 12, 'n_stored_per_color': 4, 'square_size': 56, 'ident_noise_std': 0.0, 'ident_max_shift': 0, 'color_only_jitter_std': 8.0}
[63/90] {'model_name': 'vit_base_patch16_clip_224.openai', 'pooling': 'mean_tokens', 'task_mode': 'color_only', 'n_per_color': 12, 'n_stored_per_color': 6, 'square_size': 56, 'ident_noise_std': 0.0, 'ident_max_shift': 0, 'color_only_jitter_std': 8.0}
[64/90] {'model_name': 'vit_base_patch16_clip_224.openai', 'pooling': 'mean_tokens', 'task_mode': 'color_only', 'n_per_color': 12, 'n_stored_per_color': 2, 'square_size': 56, 'ident_noise_std': 5.0, 'ident_max_shift': 2, 'color_only_jitter_std': 8.0}
[65/90] {'model_name': 'vit_base_patch16_clip_224.openai', 'pooling': 'mean_tokens', 'task_mode': 'color_only', 'n_per_color': 12, 'n_stored_per_color': 4, 'square_size': 56, 'ident_noise_std': 5.0, 'ident_max_shift': 2, 'color_only_jitter_std': 8.0}
[66/90] {'model_name': 'vit_base_patch16_clip_224.openai', 'pooling': 'mean_tokens', 'task_mode': 'color_only', 'n_per_color': 12, 'n_stored_per_color': 6, 'square_size': 56, 'ident_noise_std': 5.0, 'ident_max_shift': 2, 'color_only_jitter_std': 8.0}
[67/90] {'model_name': 'vit_base_patch16_clip_224.openai', 'pooling': 'mean_tokens', 'task_mode': 'position_only', 'n_per_color': 12, 'n_stored_per_color': 2, 'square_size': 56, 'ident_noise_std': 0.0, 'ident_max_shift': 0, 'color_only_jitter_std': 0.0}
[68/90] {'model_name': 'vit_base_patch16_clip_224.openai', 'pooling': 'mean_tokens', 'task_mode': 'position_only', 'n_per_color': 12, 'n_stored_per_color': 4, 'square_size': 56, 'ident_noise_std': 0.0, 'ident_max_shift': 0, 'color_only_jitter_std': 0.0}
[69/90] {'model_name': 'vit_base_patch16_clip_224.openai', 'pooling': 'mean_tokens', 'task_mode': 'position_only', 'n_per_color': 12, 'n_stored_per_color': 6, 'square_size': 56, 'ident_noise_std': 0.0, 'ident_max_shift': 0, 'color_only_jitter_std': 0.0}
[70/90] {'model_name': 'vit_base_patch16_clip_224.openai', 'pooling': 'mean_tokens', 'task_mode': 'position_only', 'n_per_color': 12, 'n_stored_per_color': 2, 'square_size': 56, 'ident_noise_std': 5.0, 'ident_max_shift': 2, 'color_only_jitter_std': 0.0}
[71/90] {'model_name': 'vit_base_patch16_clip_224.openai', 'pooling': 'mean_tokens', 'task_mode': 'position_only', 'n_per_color': 12, 'n_stored_per_color': 4, 'square_size': 56, 'ident_noise_std': 5.0, 'ident_max_shift': 2, 'color_only_jitter_std': 0.0}
[72/90] {'model_name': 'vit_base_patch16_clip_224.openai', 'pooling': 'mean_tokens', 'task_mode': 'position_only', 'n_per_color': 12, 'n_stored_per_color': 6, 'square_size': 56, 'ident_noise_std': 5.0, 'ident_max_shift': 2, 'color_only_jitter_std': 0.0}
[73/90] {'model_name': 'convnext_tiny', 'pooling': 'auto', 'task_mode': 'mixed_color_position', 'n_per_color': 12, 'n_stored_per_color': 2, 'square_size': 56, 'ident_noise_std': 0.0, 'ident_max_shift': 0, 'color_only_jitter_std': 0.0}
[74/90] {'model_name': 'convnext_tiny', 'pooling': 'auto', 'task_mode': 'mixed_color_position', 'n_per_color': 12, 'n_stored_per_color': 4, 'square_size': 56, 'ident_noise_std': 0.0, 'ident_max_shift': 0, 'color_only_jitter_std': 0.0}
[75/90] {'model_name': 'convnext_tiny', 'pooling': 'auto', 'task_mode': 'mixed_color_position', 'n_per_color': 12, 'n_stored_per_color': 6, 'square_size': 56, 'ident_noise_std': 0.0, 'ident_max_shift': 0, 'color_only_jitter_std': 0.0}
[76/90] {'model_name': 'convnext_tiny', 'pooling': 'auto', 'task_mode': 'mixed_color_position', 'n_per_color': 12, 'n_stored_per_color': 2, 'square_size': 56, 'ident_noise_std': 5.0, 'ident_max_shift': 2, 'color_only_jitter_std': 0.0}
[77/90] {'model_name': 'convnext_tiny', 'pooling': 'auto', 'task_mode': 'mixed_color_position', 'n_per_color': 12, 'n_stored_per_color': 4, 'square_size': 56, 'ident_noise_std': 5.0, 'ident_max_shift': 2, 'color_only_jitter_std': 0.0}
[78/90] {'model_name': 'convnext_tiny', 'pooling': 'auto', 'task_mode': 'mixed_color_position', 'n_per_color': 12, 'n_stored_per_color': 6, 'square_size': 56, 'ident_noise_std': 5.0, 'ident_max_shift': 2, 'color_only_jitter_std': 0.0}
[79/90] {'model_name': 'convnext_tiny', 'pooling': 'auto', 'task_mode': 'color_only', 'n_per_color': 12, 'n_stored_per_color': 2, 'square_size': 56, 'ident_noise_std': 0.0, 'ident_max_shift': 0, 'color_only_jitter_std': 8.0}
[80/90] {'model_name': 'convnext_tiny', 'pooling': 'auto', 'task_mode': 'color_only', 'n_per_color': 12, 'n_stored_per_color': 4, 'square_size': 56, 'ident_noise_std': 0.0, 'ident_max_shift': 0, 'color_only_jitter_std': 8.0}
[81/90] {'model_name': 'convnext_tiny', 'pooling': 'auto', 'task_mode': 'color_only', 'n_per_color': 12, 'n_stored_per_color': 6, 'square_size': 56, 'ident_noise_std': 0.0, 'ident_max_shift': 0, 'color_only_jitter_std': 8.0}
[82/90] {'model_name': 'convnext_tiny', 'pooling': 'auto', 'task_mode': 'color_only', 'n_per_color': 12, 'n_stored_per_color': 2, 'square_size': 56, 'ident_noise_std': 5.0, 'ident_max_shift': 2, 'color_only_jitter_std': 8.0}
[83/90] {'model_name': 'convnext_tiny', 'pooling': 'auto', 'task_mode': 'color_only', 'n_per_color': 12, 'n_stored_per_color': 4, 'square_size': 56, 'ident_noise_std': 5.0, 'ident_max_shift': 2, 'color_only_jitter_std': 8.0}

{'models': ['convnext_tiny',
  'vit_base_patch16_224',
  'vit_base_patch16_clip_224.openai'],
 'n_rows': 270,
 'best_identification': {'vit_base_patch16_224': {'model_name': 'vit_base_patch16_224',
   'seed': 0,
   'metric': 'cosine',
   'preprocess_mode': 'l2_only',
   'task_mode': 'position_only',
   'pooling': 'mean_tokens',
   'n_per_color': 12,
   'run_n_per_color': 72,
   'n_stored_per_color': 2,
   'square_size': 56,
   'ident_noise_std': 0.0,
   'ident_max_shift': 0,
   'color_only_jitter_std': 0.0,
   'layer': 'layer_6',
   'ident_accuracy': 100.0,
   'ident_avg_target_sim': 1.0000000596036447,
   'ident_avg_best_wrong_sim': 0.9657242894163011,
   'ident_avg_margin': 0.034275770187343624,
   'gen_accuracy': 51.42857142857142,
   'gen_avg_target_sim': 0.9695373921865534,
   'gen_avg_best_wrong_sim': 0.9689634140610016,
   'gen_avg_margin': 0.000573978125551671,
   'avg_margin': 0.017424874156447646},
  'vit_base_patch16_clip_224.openai': {'model_name': 'vit_base_patch16_clip_224.openai',
   'seed': 0,
   'metric': 'cosine',
   'preprocess_mode': 'l2_only',
   'task_mode': 'position_only',
   'pooling': 'cls',
   'n_per_color': 12,
   'run_n_per_color': 72,
   'n_stored_per_color': 2,
   'square_size': 56,
   'ident_noise_std': 0.0,
   'ident_max_shift': 0,
   'color_only_jitter_std': 0.0,
   'layer': 'layer_11',
   'ident_accuracy': 100.0,
   'ident_avg_target_sim': 1.0000000894059706,
   'ident_avg_best_wrong_sim': 0.9427691663952679,
   'ident_avg_margin': 0.05723092301070276,
   'gen_accuracy': 50.0,
   'gen_avg_target_sim': 0.9539393354447433,
   'gen_avg_best_wrong_sim': 0.9579870857029044,
   'gen_avg_margin': -0.004047750258160806,
   'avg_margin': 0.026591586376270977},
  'convnext_tiny': {'model_name': 'convnext_tiny',
   'seed': 0,
   'metric': 'cosine',
   'preprocess_mode': 'l2_only',
   'task_mode': 'mixed_color_position',
   'pooling': 'auto',
   'n_per_color': 12,
   'run_n_per_color': 12,
   'n_stored_per_color': 2,
   'square_size': 56,
   'ident_noise_std': 0.0,
   'ident_max_shift': 0,
   'color_only_jitter_std': 0.0,
   'layer': 'layer_3',
   'ident_accuracy': 100.0,
   'ident_avg_target_sim': 1.0000000298013252,
   'ident_avg_best_wrong_sim': 0.9837699472271436,
   'ident_avg_margin': 0.016230082574181643,
   'gen_accuracy': 36.666666666666664,
   'gen_avg_target_sim': 0.9707198756771989,
   'gen_avg_best_wrong_sim': 0.9819491959811436,
   'gen_avg_margin': -0.011229320303944766,
   'avg_margin': 0.0025003811351184384}},
 'best_generalization': {'vit_base_patch16_224': {'model_name': 'vit_base_patch16_224',
   'seed': 0,
   'metric': 'cosine',
   'preprocess_mode': 'l2_only',
   'task_mode': 'color_only',
   'pooling': 'mean_tokens',
   'n_per_color': 12,
   'run_n_per_color': 12,
   'n_stored_per_color': 2,
   'square_size': 56,
   'ident_noise_std': 0.0,
   'ident_max_shift': 0,
   'color_only_jitter_std': 8.0,
   'layer': 'layer_11',
   'ident_accuracy': 100.0,
   'ident_avg_target_sim': 1.0000000298013265,
   'ident_avg_best_wrong_sim': 0.9995760718600916,
   'ident_avg_margin': 0.0004239579412347964,
   'gen_accuracy': 93.33333333333333,
   'gen_avg_target_sim': 0.9998059858705293,
   'gen_avg_best_wrong_sim': 0.9994630127768136,
   'gen_avg_margin': 0.0003429730937156835,
   'avg_margin': 0.00038346551747523995},
  'vit_base_patch16_clip_224.openai': {'model_name': 'vit_base_patch16_clip_224.openai',
   'seed': 0,
   'metric': 'cosine',
   'preprocess_mode': 'l2_only',
   'task_mode': 'color_only',
   'pooling': 'cls',
   'n_per_color': 12,
   'run_n_per_color': 12,
   'n_stored_per_color': 2,
   'square_size': 56,
   'ident_noise_std': 0.0,
   'ident_max_shift': 0,
   'color_only_jitter_std': 8.0,
   'layer': 'layer_11',
   'ident_accuracy': 100.0,
   'ident_avg_target_sim': 1.0000000298013234,
   'ident_avg_best_wrong_sim': 0.9971282480282976,
   'ident_avg_margin': 0.0028717817730258,
   'gen_accuracy': 93.33333333333333,
   'gen_avg_target_sim': 0.9982914278479945,
   'gen_avg_best_wrong_sim': 0.9959996152418865,
   'gen_avg_margin': 0.0022918126061080143,
   'avg_margin': 0.002581797189566907},
  'convnext_tiny': {'model_name': 'convnext_tiny',
   'seed': 0,
   'metric': 'cosine',
   'preprocess_mode': 'l2_only',
   'task_mode': 'color_only',
   'pooling': 'auto',
   'n_per_color': 12,
   'run_n_per_color': 12,
   'n_stored_per_color': 2,
   'square_size': 56,
   'ident_noise_std': 0.0,
   'ident_max_shift': 0,
   'color_only_jitter_std': 8.0,
   'layer': 'layer_0',
   'ident_accuracy': 100.0,
   'ident_avg_target_sim': 1.000000034768379,
   'ident_avg_best_wrong_sim': 0.9999974270649546,
   'ident_avg_margin': 2.6077034243713695e-06,
   'gen_accuracy': 93.33333333333333,
   'gen_avg_target_sim': 0.9999988605567857,
   'gen_avg_best_wrong_sim': 0.999996750552201,
   'gen_avg_margin': 2.11000458480252e-06,
   'avg_margin': 2.3588540045869447e-06}},
 'best_margin': {'vit_base_patch16_224': {'model_name': 'vit_base_patch16_224',
   'seed': 0,
   'metric': 'cosine',
   'preprocess_mode': 'l2_only',
   'task_mode': 'position_only',
   'pooling': 'mean_tokens',
   'n_per_color': 12,
   'run_n_per_color': 72,
   'n_stored_per_color': 2,
   'square_size': 56,
   'ident_noise_std': 0.0,
   'ident_max_shift': 0,
   'color_only_jitter_std': 0.0,
   'layer': 'layer_6',
   'ident_accuracy': 100.0,
   'ident_avg_target_sim': 1.0000000596036447,
   'ident_avg_best_wrong_sim': 0.9657242894163011,
   'ident_avg_margin': 0.034275770187343624,
   'gen_accuracy': 51.42857142857142,
   'gen_avg_target_sim': 0.9695373921865534,
   'gen_avg_best_wrong_sim': 0.9689634140610016,
   'gen_avg_margin': 0.000573978125551671,
   'avg_margin': 0.017424874156447646},
  'vit_base_patch16_clip_224.openai': {'model_name': 'vit_base_patch16_clip_224.openai',
   'seed': 0,
   'metric': 'cosine',
   'preprocess_mode': 'l2_only',
   'task_mode': 'position_only',
   'pooling': 'cls',
   'n_per_color': 12,
   'run_n_per_color': 72,
   'n_stored_per_color': 2,
   'square_size': 56,
   'ident_noise_std': 0.0,
   'ident_max_shift': 0,
   'color_only_jitter_std': 0.0,
   'layer': 'layer_11',
   'ident_accuracy': 100.0,
   'ident_avg_target_sim': 1.0000000894059706,
   'ident_avg_best_wrong_sim': 0.9427691663952679,
   'ident_avg_margin': 0.05723092301070276,
   'gen_accuracy': 50.0,
   'gen_avg_target_sim': 0.9539393354447433,
   'gen_avg_best_wrong_sim': 0.9579870857029044,
   'gen_avg_margin': -0.004047750258160806,
   'avg_margin': 0.026591586376270977},
  'convnext_tiny': {'model_name': 'convnext_tiny',
   'seed': 0,
   'metric': 'cosine',
   'preprocess_mode': 'l2_only',
   'task_mode': 'position_only',
   'pooling': 'auto',
   'n_per_color': 12,
   'run_n_per_color': 72,
   'n_stored_per_color': 2,
   'square_size': 56,
   'ident_noise_std': 0.0,
   'ident_max_shift': 0,
   'color_only_jitter_std': 0.0,
   'layer': 'layer_3',
   'ident_accuracy': 100.0,
   'ident_avg_target_sim': 1.0000000894059706,
   'ident_avg_best_wrong_sim': 0.991945206637893,
   'ident_avg_margin': 0.008054882768077642,
   'gen_accuracy': 55.714285714285715,
   'gen_avg_target_sim': 0.9861895911893135,
   'gen_avg_best_wrong_sim': 0.9857886714865026,
   'gen_avg_margin': 0.0004009197028109376,
   'avg_margin': 0.00422790123544429}},
 'tradeoff_candidates': [],
 'n_tradeoff_candidates': 0,
 'sanity_all_pass': True}

In [4]:
# This table shows raw rows from the combined synthetic benchmark CSV.
# Each row is one experimental condition: model, task_mode, pooling, layer, storage size,
# and the resulting identification/generalization metrics.
# Useful fields:
# - ident_accuracy / gen_accuracy: retrieval accuracy for the two tasks
# - ident_avg_margin / gen_avg_margin: how far the correct target is from the best wrong item
# - avg_margin: average of the identification and generalization margins
# Read this as the row-level data behind the later summary tables.

combined = pd.read_csv(OUTPUT_DIR / "model_comparison_combined.csv")
combined.head()

,model_name,seed,metric,preprocess_mode,task_mode,pooling,n_per_color,run_n_per_color,n_stored_per_color,square_size,...,layer,ident_accuracy,ident_avg_target_sim,ident_avg_best_wrong_sim,ident_avg_margin,gen_accuracy,gen_avg_target_sim,gen_avg_best_wrong_sim,gen_avg_margin,avg_margin
0,vit_base_patch16_224,0,cosine,l2_only,mixed_color_position,cls,12,12,2,56,...,layer_0,100.0,1.0,0.999991,0.000009,60.000000,0.999992,0.999990,1.657009e-06,0.000005
1,vit_base_patch16_224,0,cosine,l2_only,mixed_color_position,cls,12,12,2,56,...,layer_11,100.0,1.0,0.998164,0.001836,46.666667,0.996962,0.997428,-4.658173e-04,0.000685
2,vit_base_patch16_224,0,cosine,l2_only,mixed_color_position,cls,12,12,2,56,...,layer_6,100.0,1.0,0.998477,0.001523,50.000000,0.997958,0.998115,-1.570532e-04,0.000683
3,vit_base_patch16_224,0,cosine,l2_only,mixed_color_position,cls,12,12,4,56,...,layer_0,100.0,1.0,0.999994,0.000006,54.166667,0.999993,0.999993,-4.966849e-09,0.000003
4,vit_base_patch16_224,0,cosine,l2_only,mixed_color_position,cls,12,12,4,56,...,layer_11,100.0,1.0,0.998440,0.001560,25.000000,0.997217,0.997843,-6.259393e-04,0.000467

In [5]:
# These two tables show the best row per model under two criteria.
# best_ident: for each model, the condition with the highest identification accuracy.
# best_gen: for each model, the condition with the highest generalization accuracy.
# Fields:
# - task_mode: synthetic task family (mixed_color_position, color_only, position_only)
# - pooling: feature readout used for the backbone
# - layer: representation layer being evaluated
# - n_stored_per_color: how many stored examples per color were used
# - ident_accuracy / gen_accuracy: percent correct on the two tasks
# - avg_margin: average separation of the correct target from competitors
# tradeoff_candidates is the key result: an empty list means the desired synthetic tradeoff
# did not appear in this model-comparison pass.

summary_path = OUTPUT_DIR / "model_comparison_summary.json"
summary_json = json.loads(summary_path.read_text())

best_ident = pd.DataFrame(summary_json["best_identification"]).T[
    ["task_mode", "pooling", "layer", "n_stored_per_color", "ident_accuracy", "gen_accuracy", "avg_margin"]
]
best_gen = pd.DataFrame(summary_json["best_generalization"]).T[
    ["task_mode", "pooling", "layer", "n_stored_per_color", "ident_accuracy", "gen_accuracy", "avg_margin"]
]

display(best_ident)
display(best_gen)
summary_json["tradeoff_candidates"]

,task_mode,pooling,layer,n_stored_per_color,ident_accuracy,gen_accuracy,avg_margin
vit_base_patch16_224,position_only,mean_tokens,layer_6,2,100.0,51.428571,0.017425
vit_base_patch16_clip_224.openai,position_only,cls,layer_11,2,100.0,50.0,0.026592
convnext_tiny,mixed_color_position,auto,layer_3,2,100.0,36.666667,0.0025

,task_mode,pooling,layer,n_stored_per_color,ident_accuracy,gen_accuracy,avg_margin
vit_base_patch16_224,color_only,mean_tokens,layer_11,2,100.0,93.333333,0.000383
vit_base_patch16_clip_224.openai,color_only,cls,layer_11,2,100.0,93.333333,0.002582
convnext_tiny,color_only,auto,layer_0,2,100.0,93.333333,0.000002

[]

In [6]:
# This table directly compares ViT and CLIP on the synthetic benchmark.
# Rows are grouped by model, task_mode, pooling, and layer, then averaged over the other
# synthetic settings such as storage size and perturbation condition.
# Fields:
# - ident_accuracy / gen_accuracy: mean performance for that grouped condition
# - ident_avg_margin / gen_avg_margin: mean margin on each task
# - avg_margin: overall mean margin across both tasks
# Main finding: CLIP behaves similarly on easy color-only conditions but does not fix the
# harder synthetic mixed or position-heavy settings.

vit_vs_clip = combined[combined["model_name"].isin(["vit_base_patch16_224", "vit_base_patch16_clip_224.openai"])]
vit_vs_clip.groupby(["model_name", "task_mode", "pooling", "layer"]).agg({
    "ident_accuracy": "mean",
    "gen_accuracy": "mean",
    "ident_avg_margin": "mean",
    "gen_avg_margin": "mean",
    "avg_margin": "mean",
}).sort_values(["task_mode", "gen_accuracy"], ascending=[True, False]).head(18)

                                                                            ident_accuracy  \
model_name                       task_mode            pooling     layer
vit_base_patch16_224             color_only           mean_tokens layer_0        62.268519
vit_base_patch16_clip_224.openai color_only           mean_tokens layer_6        54.629630
vit_base_patch16_224             color_only           cls         layer_6        55.787037
vit_base_patch16_clip_224.openai color_only           mean_tokens layer_0        62.962963
vit_base_patch16_224             color_only           cls         layer_0        77.314815
                                                                  layer_11       57.638889
                                                      mean_tokens layer_11       57.638889
vit_base_patch16_clip_224.openai color_only           cls         layer_6        55.092593
                                                                  layer_11       71.296296
vit_base_patch16_224             color_only           mean_tokens layer_6        57.638889
vit_base_patch16_clip_224.openai color_only           mean_tokens layer_11       61.342593
                                                      cls         layer_0        73.379630
vit_base_patch16_224             mixed_color_position mean_tokens layer_0        77.314815
                                                      cls         layer_0       100.000000
vit_base_patch16_clip_224.openai mixed_color_position mean_tokens layer_0        75.925926
                                                      cls         layer_11       72.685185
                                                      mean_tokens layer_11       67.129630
                                                      cls         layer_6        72.685185

                                                                            gen_accuracy  \
model_name                       task_mode            pooling     layer
vit_base_patch16_224             color_only           mean_tokens layer_0      88.564815
vit_base_patch16_clip_224.openai color_only           mean_tokens layer_6      88.194444
vit_base_patch16_224             color_only           cls         layer_6      88.055556
vit_base_patch16_clip_224.openai color_only           mean_tokens layer_0      87.083333
vit_base_patch16_224             color_only           cls         layer_0      86.666667
                                                                  layer_11     86.666667
                                                      mean_tokens layer_11     86.666667
vit_base_patch16_clip_224.openai color_only           cls         layer_6      85.833333
                                                                  layer_11     85.046296
vit_base_patch16_224             color_only           mean_tokens layer_6      84.953704
vit_base_patch16_clip_224.openai color_only           mean_tokens layer_11     82.592593
                                                      cls         layer_0      79.537037
vit_base_patch16_224             mixed_color_position mean_tokens layer_0      67.037037
                                                      cls         layer_0      59.351852
vit_base_patch16_clip_224.openai mixed_color_position mean_tokens layer_0      58.009259
                                                      cls         layer_11     42.546296
                                                      mean_tokens layer_11     42.268519
                                                      cls         layer_6      41.805556

                                                                            ident_avg_margin  \
model_name                       task_mode            pooling     layer
vit_base_patch16_224             color_only           mean_tokens layer_0      -2.023130e-05
vit_base_patch16_clip_224.openai color_only           mean_tokens layer_6      -1.054519e-03
vit_base_patch16_224             color_only           cls         layer_6      -5.316036e-04
vit_base_patch16_clip_224.openai color_only           mean_tokens layer_0      -3.534645e-05
vit_base_patch16_224             color_only           cls         layer_0      -2.179985e-08
                                                                  layer_11     -6.435067e-04
                                                      mean_tokens layer_11     -3.395041e-03
vit_base_patch16_clip_224.openai color_only           cls         layer_6      -2.686705e-03
                                                                  layer_11     -1.253141e-03
vit_base_patch16_224             color_only           mean_tokens layer_6      -1.852152e-03
vit_base_patch16_clip_224.openai color_only           mean_tokens layer_11     -6.407794e-04
                                                      cls         layer_0      -3.986891e-06
vit_base_patch16_224             mixed_color_position mean_tokens layer_0       1.120654e-03
                                                      cls         layer_0       6.582450e-06
vit_base_patch16_clip_224.openai mixed_color_position mean_tokens layer_0       8.594240e-04
                                                      cls         layer_11      1.547882e-02
                                                      mean_tokens layer_11      3.008535e-03
                                                      cls         layer_6       2.913612e-03

                                                                            gen_avg_margin  \
model_name                       task_mode            pooling     layer
vit_base_patch16_224             color_only           mean_tokens layer_0     1.122480e-05
vit_base_patch16_clip_224.openai color_only           mean_tokens layer_6     3.586486e-05
vit_base_patch16_224             color_only           cls         layer_6     6.905811e-05
vit_base_patch16_clip_224.openai color_only           mean_tokens layer_0     4.429012e-06
vit_base_patch16_224             color_only           cls         layer_0    -2.988511e-08
                                                                  layer_11    1.308562e-04
                                                      mean_tokens layer_11    1.724985e-04
vit_base_patch16_clip_224.openai color_only           cls         layer_6     1.092229e-04
                                                                  layer_11    1.238292e-03
vit_base_patch16_224             color_only           mean_tokens layer_6     1.741807e-04
vit_base_patch16_clip_224.openai color_only           mean_tokens layer_11    1.064495e-04
                                                      cls         layer_0     2.449285e-05
vit_base_patch16_224             mixed_color_position mean_tokens layer_0     2.641025e-04
                                                      cls         layer_0     9.392147e-07
vit_base_patch16_clip_224.openai mixed_color_position mean_tokens layer_0     7.302629e-05
                                                      cls         layer_11   -6.320637e-03
                                                      mean_tokens layer_11   -9.707923e-04
                                                      cls         layer_6    -1.225977e-03

                                                                              avg_margin
model_name                       task_mode            pooling     layer
vit_base_patch16_224             color_only           mean_tokens layer_0  -4.503253e-06
vit_base_patch16_clip_224.openai color_only           mean_tokens layer_6  -5.093269e-04
vit_base_patch16_224             color_only           cls         layer_6  -2.312727e-04
vit_base_patch16_clip_224.openai color_only           mean_tokens layer_0  -1.545872e-05
vit_base_patch16_224             color_only           cls         layer_0  -2.584248e-08
                                                                  layer_11 -2.563252e-04
                                                      mean_tokens layer_11 -1.611271e-03
vit_base_patch16_clip_224.openai color_only           cls         layer_6  -1.288741e-03
                                                                  layer_11 -7.424559e-06
vit_base_patch16_224             color_only           mean_tokens layer_6  -8.389858e-04
vit_base_patch16_clip_224.openai color_only           mean_tokens layer_11 -2.671650e-04
                                                      cls         layer_0   1.025298e-05
vit_base_patch16_224             mixed_color_position mean_tokens layer_0   6.923782e-04
                                                      cls         layer_0   3.760832e-06
vit_base_patch16_clip_224.openai mixed_color_position mean_tokens layer_0   4.662251e-04
                                                      cls         layer_11  4.579093e-03
                                                      mean_tokens layer_11  1.018871e-03
                                                      cls         layer_6   8.438179e-04