# Vision Naturalistic Baseline

In [1]:
# This setup cell has no substantive output by itself.
# It imports the naturalistic baseline runner and the helpers used to summarize the saved CSVs.

from pathlib import Path
import json
import pandas as pd

from vision.run_naturalistic_baseline import get_model_specs, run_naturalistic_baseline

In [2]:
# This cell defines the benchmark configuration.
# INCLUDE_CLIP=True means the naturalistic baseline compares the original ViT, ConvNeXt,
# and CLIP image tower in the same pipeline.

DEVICE = "cpu"
BATCH_SIZE = 16
SEED = 0
INCLUDE_CLIP = True
MODEL_SPECS = get_model_specs(include_clip=INCLUDE_CLIP)
OUTPUT_DIR = Path("results/vision/naturalistic")

## Fruits

In [3]:
# This cell runs the fruits baseline.
# The summary output reports the saved artifact paths plus top-level benchmark information.
# Task definition in this notebook:
# - identification: noisy stored image -> exact stored target
# - generalization: held-out real image -> stored image with highest human similarity

fruits_summary = run_naturalistic_baseline(
    category="fruits",
    device=DEVICE,
    batch_size=BATCH_SIZE,
    seed=SEED,
    output_dir=OUTPUT_DIR,
    dataset_pkl="datasets_peterson.pkl",
    image_root=".",
    model_specs=MODEL_SPECS,
)
fruits_summary

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

{'category': 'fruits',
 'chance_accuracy_values': [1.25],
 'required_exemplars': None,
 'split_mode': 'balanced_exemplar_folds',
 'storage_sizes': [80],
 'n_seeds': None,
 'models': ['vit_base_patch16_224::cls',
  'vit_base_patch16_224::mean_tokens',
  'convnext_tiny::auto',
  'vit_base_patch16_clip_224.openai::cls',
  'vit_base_patch16_clip_224.openai::mean_tokens'],
 'sanity_all_pass': True,
 'best_generalization': {'vit_base_patch16_224::cls': {'category': 'fruits',
   'split_label': 'fold_2',
   'split_seed': 2,
   'split_mode': 'balanced_exemplar_folds',
   'model_name': 'vit_base_patch16_224',
   'pooling': 'cls',
   'layer': 'layer_11',
   'n_stored': 80,
   'n_probe': 40,
   'chance_accuracy': 1.25,
   'ident_accuracy': 100.0,
   'ident_avg_target_sim': 0.9974550186848786,
   'ident_avg_margin': 0.05835537162167862,
   'gen_accuracy': 47.5,
   'gen_avg_target_sim': 0.932647384322044,
   'gen_avg_margin': -0.008146042945666726,
   'gen_avg_retrieved_human_similarity': 0.72425,
   'gen_avg_human_similarity_regret': 0.090555555,
   'gen_same_concept_accuracy': 87.5,
   'human_rdm_spearman': 0.2637852824986545,
   'exact_accuracy': 100.0,
   'clean_reextract_accuracy': 100.0,
   'exact_avg_target_sim': 1.000000032781556,
   'clean_reextract_avg_target_sim': 1.000000032781556},
  'vit_base_patch16_224::mean_tokens': {'category': 'fruits',
   'split_label': 'fold_2',
   'split_seed': 2,
   'split_mode': 'balanced_exemplar_folds',
   'model_name': 'vit_base_patch16_224',
   'pooling': 'mean_tokens',
   'layer': 'layer_11',
   'n_stored': 80,
   'n_probe': 40,
   'chance_accuracy': 1.25,
   'ident_accuracy': 100.0,
   'ident_avg_target_sim': 0.9964709451090794,
   'ident_avg_margin': 0.10414225562259402,
   'gen_accuracy': 52.5,
   'gen_avg_target_sim': 0.8801058143625818,
   'gen_avg_margin': -0.009874287835166886,
   'gen_avg_retrieved_human_similarity': 0.710805555,
   'gen_avg_human_similarity_regret': 0.10400000000000001,
   'gen_same_concept_accuracy': 85.0,
   'human_rdm_spearman': 0.33812324222519313,
   'exact_accuracy': 100.0,
   'clean_reextract_accuracy': 100.0,
   'exact_avg_target_sim': 1.000000033526614,
   'clean_reextract_avg_target_sim': 1.000000033526614},
  'convnext_tiny::auto': {'category': 'fruits',
   'split_label': 'fold_1',
   'split_seed': 1,
   'split_mode': 'balanced_exemplar_folds',
   'model_name': 'convnext_tiny',
   'pooling': 'auto',
   'layer': 'layer_3',
   'n_stored': 80,
   'n_probe': 40,
   'chance_accuracy': 1.25,
   'ident_accuracy': 100.0,
   'ident_avg_target_sim': 0.9894380596359282,
   'ident_avg_margin': 0.19704572406452076,
   'gen_accuracy': 50.0,
   'gen_avg_target_sim': 0.7456085379840813,
   'gen_avg_margin': -0.033903308870322384,
   'gen_avg_retrieved_human_similarity': 0.7108055550000001,
   'gen_avg_human_similarity_regret': 0.09725000000000002,
   'gen_same_concept_accuracy': 77.5,
   'human_rdm_spearman': 0.2977470615311246,
   'exact_accuracy': 100.0,
   'clean_reextract_accuracy': 100.0,
   'exact_avg_target_sim': 1.0000000260760329,
   'clean_reextract_avg_target_sim': 1.0000000260760329},
  'vit_base_patch16_clip_224.openai::cls': {'category': 'fruits',
   'split_label': 'fold_2',
   'split_seed': 2,
   'split_mode': 'balanced_exemplar_folds',
   'model_name': 'vit_base_patch16_clip_224.openai',
   'pooling': 'cls',
   'layer': 'layer_11',
   'n_stored': 80,
   'n_probe': 40,
   'chance_accuracy': 1.25,
   'ident_accuracy': 100.0,
   'ident_avg_target_sim': 0.9694094650039448,
   'ident_avg_margin': 0.15693757263434654,
   'gen_accuracy': 55.00000000000001,
   'gen_avg_target_sim': 0.798619654379161,
   'gen_avg_margin': -0.0019164408017485757,
   'gen_avg_retrieved_human_similarity': 0.725805555,
   'gen_avg_human_similarity_regret': 0.089,
   'gen_same_concept_accuracy': 67.5,
   'human_rdm_spearman': 0.5796354798251985,
   'exact_accuracy': 100.0,
   'clean_reextract_accuracy': 100.0,
   'exact_avg_target_sim': 1.0000000156452207,
   'clean_reextract_avg_target_sim': 1.0000000156452207},
  'vit_base_patch16_clip_224.openai::mean_tokens': {'category': 'fruits',
   'split_label': 'fold_1',
   'split_seed': 1,
   'split_mode': 'balanced_exemplar_folds',
   'model_name': 'vit_base_patch16_clip_224.openai',
   'pooling': 'mean_tokens',
   'layer': 'layer_11',
   'n_stored': 80,
   'n_probe': 40,
   'chance_accuracy': 1.25,
   'ident_accuracy': 100.0,
   'ident_avg_target_sim': 0.9955583861567302,
   'ident_avg_margin': 0.0729400268976074,
   'gen_accuracy': 47.5,
   'gen_avg_target_sim': 0.907241635769908,
   'gen_avg_margin': -0.015582359869672987,
   'gen_avg_retrieved_human_similarity': 0.6494166675,
   'gen_avg_human_similarity_regret': 0.1586388875,
   'gen_same_concept_accuracy': 57.49999999999999,
   'human_rdm_spearman': 0.48125634610292334,
   'exact_accuracy': 100.0,
   'clean_reextract_accuracy': 100.0,
   'exact_avg_target_sim': 1.0000000305463823,
   'clean_reextract_avg_target_sim': 1.0000000305463823}},
 'best_alignment': {'vit_base_patch16_224::cls': {'category': 'fruits',
   'split_label': 'fold_0',
   'split_seed': 0,
   'split_mode': 'balanced_exemplar_folds',
   'model_name': 'vit_base_patch16_224',
   'pooling': 'cls',
   'layer': 'layer_6',
   'n_stored': 80,
   'n_probe': 40,
   'chance_accuracy': 1.25,
   'ident_accuracy': 100.0,
   'ident_avg_target_sim': 0.9960909789722509,
   'ident_avg_margin': 0.02887386397297209,
   'gen_accuracy': 7.5,
   'gen_avg_target_sim': 0.9503110797973031,
   'gen_avg_margin': -0.019156433290415643,
   'gen_avg_retrieved_human_similarity': 0.40538889000000006,
   'gen_avg_human_similarity_regret': 0.39411111,
   'gen_same_concept_accuracy': 17.5,
   'human_rdm_spearman': 0.29780554246648155,
   'exact_accuracy': 100.0,
   'clean_reextract_accuracy': 100.0,
   'exact_avg_target_sim': 1.0000000298013243,
   'clean_reextract_avg_target_sim': 1.0000000298013243},
  'vit_base_patch16_224::mean_tokens': {'category': 'fruits',
   'split_label': 'fold_0',
   'split_seed': 0,
   'split_mode': 'balanced_exemplar_folds',
   'model_name': 'vit_base_patch16_224',
   'pooling': 'mean_tokens',
   'layer': 'layer_6',
   'n_stored': 80,
   'n_probe': 40,
   'chance_accuracy': 1.25,
   'ident_accuracy': 100.0,
   'ident_avg_target_sim': 0.9935496119514049,
   'ident_avg_margin': 0.15569701863038166,
   'gen_accuracy': 12.5,
   'gen_avg_target_sim': 0.7663106034951339,
   'gen_avg_margin': -0.06886576187373683,
   'gen_avg_retrieved_human_similarity': 0.47074999999999995,
   'gen_avg_human_similarity_regret': 0.32875,
   'gen_same_concept_accuracy': 22.5,
   'human_rdm_spearman': 0.37934279661768106,
   'exact_accuracy': 100.0,
   'clean_reextract_accuracy': 100.0,
   'exact_avg_target_sim': 1.0000000201155692,
   'clean_reextract_avg_target_sim': 1.0000000201155692},
  'convnext_tiny::auto': {'category': 'fruits',
   'split_label': 'fold_0',
   'split_seed': 0,
   'split_mode': 'balanced_exemplar_folds',
   'model_name': 'convnext_tiny',
   'pooling': 'auto',
   'layer': 'layer_2',
   'n_stored': 80,
   'n_probe': 40,
   'chance_accuracy': 1.25,
   'ident_accuracy': 100.0,
   'ident_avg_target_sim': 0.9999870173615613,
   'ident_avg_margin': 0.0005071573207679758,
   'gen_accuracy': 15.0,
   'gen_avg_target_sim': 0.9992574020925673,
   'gen_avg_margin': -0.00022946894466177036,
   'gen_avg_retrieved_human_similarity': 0.546194445,
   'gen_avg_human_similarity_regret': 0.25330555499999996,
   'gen_same_concept_accuracy': 37.5,
   'human_rdm_spearman': 0.37771650462440576,
   'exact_accuracy': 100.0,
   'clean_reextract_accuracy': 100.0,
   'exact_avg_target_sim': 1.0000000558783566,
   'clean_reextract_avg_target_sim': 1.0000000558783566},
  'vit_base_patch16_clip_224.openai::cls': {'category': 'fruits',
   'split_label': 'fold_0',
   'split_seed': 0,
   'split_mode': 'balanced_exemplar_folds',
   'model_name': 'vit_base_patch16_clip_224.openai',
   'pooling': 'cls',
   'layer': 'layer_11',
   'n_stored': 80,
   'n_probe': 40,
   'chance_accuracy': 1.25,
   'ident_accuracy': 100.0,
   'ident_avg_target_sim': 0.9685257879461627,
   'ident_avg_margin': 0.16232745397708742,
   'gen_accuracy': 40.0,
   'gen_avg_target_sim': 0.8013226991301957,
   'gen_avg_margin': -0.010380440193656592,
   'gen_avg_retrieved_human_similarity': 0.6627777775,
   'gen_avg_human_similarity_regret': 0.1367222225,
   'gen_same_concept_accuracy': 60.0,
   'human_rdm_spearman': 0.5796354798251985,
   'exact_accuracy': 100.0,
   'clean_reextract_accuracy': 100.0,
   'exact_avg_target_sim': 1.0000000186254525,
   'clean_reextract_avg_target_sim': 1.0000000186254525},
  'vit_base_patch16_clip_224.openai::mean_tokens': {'category': 'fruits',
   'split_label': 'fold_0',
   'split_seed': 0,
   'split_mode': 'balanced_exemplar_folds',
   'model_name': 'vit_base_patch16_clip_224.openai',
   'pooling': 'mean_tokens',
   'layer': 'layer_11',
   'n_stored': 80,
   'n_probe': 40,
   'chance_accuracy': 1.25,
   'ident_accuracy': 100.0,
   'ident_avg_target_sim': 0.9952650664171692,
   'ident_avg_margin': 0.07228161287837977,
   'gen_accuracy': 27.500000000000004,
   'gen_avg_target_sim': 0.90156372344684,
   'gen_avg_margin': -0.019547065500928378,
   'gen_avg_retrieved_human_similarity': 0.6047499999999999,
   'gen_avg_human_similarity_regret': 0.19475,
   'gen_same_concept_accuracy': 40.0,
   'human_rdm_spearman': 0.48125634610292334,
   'exact_accuracy': 100.0,
   'clean_reextract_accuracy': 100.0,
   'exact_avg_target_sim': 1.0000000342716728,
   'clean_reextract_avg_target_sim': 1.0000000342716728}},
 'best_margin': {'vit_base_patch16_224::cls': {'category': 'fruits',
   'split_label': 'fold_0',
   'split_seed': 0,
   'split_mode': 'balanced_exemplar_folds',
   'model_name': 'vit_base_patch16_224',
   'pooling': 'cls',
   'layer': 'layer_0',
   'n_stored': 80,
   'n_probe': 40,
   'chance_accuracy': 1.25,
   'ident_accuracy': 100.0,
   'ident_avg_target_sim': 0.9999978005875032,
   'ident_avg_margin': 5.8554860090771765e-05,
   'gen_accuracy': 5.0,
   'gen_avg_target_sim': 0.9996972501149823,
   'gen_avg_margin': -0.00024020523902449075,
   'gen_avg_retrieved_human_similarity': 0.2835,
   'gen_avg_human_similarity_regret': 0.516,
   'gen_same_concept_accuracy': 7.5,
   'human_rdm_spearman': 0.1271121890665281,
   'exact_accuracy': 100.0,
   'clean_reextract_accuracy': 100.0,
   'exact_avg_target_sim': 1.0000000275661496,
   'clean_reextract_avg_target_sim': 1.0000000275661496},
  'vit_base_patch16_224::mean_tokens': {'category': 'fruits',
   'split_label': 'fold_2',
   'split_seed': 2,
   'split_mode': 'balanced_exemplar_folds',
   'model_name': 'vit_base_patch16_224',
   'pooling': 'mean_tokens',
   'layer': 'layer_11',
   'n_stored': 80,
   'n_probe': 40,
   'chance_accuracy': 1.25,
   'ident_accuracy': 100.0,
   'ident_avg_target_sim': 0.9964709451090794,
   'ident_avg_margin': 0.10414225562259402,
   'gen_accuracy': 52.5,
   'gen_avg_target_sim': 0.8801058143625818,
   'gen_avg_margin': -0.009874287835166886,
   'gen_avg_retrieved_human_similarity': 0.710805555,
   'gen_avg_human_similarity_regret': 0.10400000000000001,
   'gen_same_concept_accuracy': 85.0,
   'human_rdm_spearman': 0.33812324222519313,
   'exact_accuracy': 100.0,
   'clean_reextract_accuracy': 100.0,
   'exact_avg_target_sim': 1.000000033526614,
   'clean_reextract_avg_target_sim': 1.000000033526614},
  'convnext_tiny::auto': {'category': 'fruits',
   'split_label': 'fold_1',
   'split_seed': 1,
   'split_mode': 'balanced_exemplar_folds',
   'model_name': 'convnext_tiny',
   'pooling': 'auto',
   'layer': 'layer_2',
   'n_stored': 80,
   'n_probe': 40,
   'chance_accuracy': 1.25,
   'ident_accuracy': 100.0,
   'ident_avg_target_sim': 0.999986201522991,
   'ident_avg_margin': 0.0004905067568750892,
   'gen_accuracy': 27.500000000000004,
   'gen_avg_target_sim': 0.9993174537741639,
   'gen_avg_margin': -0.00019100308824898936,
   'gen_avg_retrieved_human_similarity': 0.560444445,
   'gen_avg_human_similarity_regret': 0.24761110999999997,
   'gen_same_concept_accuracy': 42.5,
   'human_rdm_spearman': 0.37771650462440576,
   'exact_accuracy': 100.0,
   'clean_reextract_accuracy': 100.0,
   'exact_avg_target_sim': 1.0000000469376598,
   'clean_reextract_avg_target_sim': 1.0000000469376598},
  'vit_base_patch16_clip_224.openai::cls': {'category': 'fruits',
   'split_label': 'fold_2',
   'split_seed': 2,
   'split_mode': 'balanced_exemplar_folds',
   'model_name': 'vit_base_patch16_clip_224.openai',
   'pooling': 'cls',
   'layer': 'layer_11',
   'n_stored': 80,
   'n_probe': 40,
   'chance_accuracy': 1.25,
   'ident_accuracy': 100.0,
   'ident_avg_target_sim': 0.9694094650039448,
   'ident_avg_margin': 0.15693757263434654,
   'gen_accuracy': 55.00000000000001,
   'gen_avg_target_sim': 0.798619654379161,
   'gen_avg_margin': -0.0019164408017485757,
   'gen_avg_retrieved_human_similarity': 0.725805555,
   'gen_avg_human_similarity_regret': 0.089,
   'gen_same_concept_accuracy': 67.5,
   'human_rdm_spearman': 0.5796354798251985,
   'exact_accuracy': 100.0,
   'clean_reextract_accuracy': 100.0,
   'exact_avg_target_sim': 1.0000000156452207,
   'clean_reextract_avg_target_sim': 1.0000000156452207},
  'vit_base_patch16_clip_224.openai::mean_tokens': {'category': 'fruits',
   'split_label': 'fold_2',
   'split_seed': 2,
   'split_mode': 'balanced_exemplar_folds',
   'model_name': 'vit_base_patch16_clip_224.openai',
   'pooling': 'mean_tokens',
   'layer': 'layer_11',
   'n_stored': 80,
   'n_probe': 40,
   'chance_accuracy': 1.25,
   'ident_accuracy': 100.0,
   'ident_avg_target_sim': 0.99546897917647,
   'ident_avg_margin': 0.07056034816147341,
   'gen_accuracy': 37.5,
   'gen_avg_target_sim': 0.9045831229138013,
   'gen_avg_margin': -0.012203212100078192,
   'gen_avg_retrieved_human_similarity': 0.6376666675,
   'gen_avg_human_similarity_regret': 0.1771388875,
   'gen_same_concept_accuracy': 47.5,
   'human_rdm_spearman': 0.48125634610292334,
   'exact_accuracy': 100.0,
   'clean_reextract_accuracy': 100.0,
   'exact_avg_target_sim': 1.000000030546382,
   'clean_reextract_avg_target_sim': 1.000000030546382}}}

In [4]:
# This table summarizes the fruits benchmark by model, pooling, and layer.
# Rows: one aggregated representation choice (model + pooling + layer).
# Fields:
# - ident_accuracy: mean exact-image retrieval accuracy
# - gen_accuracy: mean human-similarity generalization accuracy
# - gen_avg_margin: average gap between the correct stored target and the best wrong one
# - human_rdm_spearman: alignment between model geometry and human similarity geometry
# - gen_same_concept_accuracy: how often the retrieved stored image is from the same concept family
# Main finding: late layers retrieve best, while mid layers align best to human similarity.

fruits = pd.read_csv(OUTPUT_DIR / "fruits_combined.csv")
fruits.groupby(["model_name", "pooling", "layer"]).agg({
    "ident_accuracy": "mean",
    "gen_accuracy": "mean",
    "gen_avg_margin": "mean",
    "human_rdm_spearman": "mean",
    "gen_same_concept_accuracy": "mean",
}).sort_values("gen_accuracy", ascending=False).head(12)

                                                       ident_accuracy  \
model_name                       pooling     layer
vit_base_patch16_224             mean_tokens layer_11      100.000000
vit_base_patch16_clip_224.openai cls         layer_11      100.000000
convnext_tiny                    auto        layer_3       100.000000
vit_base_patch16_224             cls         layer_11      100.000000
vit_base_patch16_clip_224.openai mean_tokens layer_11      100.000000
convnext_tiny                    auto        layer_2       100.000000
                                             layer_0        99.166667
vit_base_patch16_224             mean_tokens layer_6       100.000000
vit_base_patch16_clip_224.openai mean_tokens layer_6       100.000000
vit_base_patch16_224             cls         layer_6       100.000000
                                 mean_tokens layer_0       100.000000
vit_base_patch16_clip_224.openai cls         layer_6        49.166667

                                                       gen_accuracy  \
model_name                       pooling     layer
vit_base_patch16_224             mean_tokens layer_11     48.333333
vit_base_patch16_clip_224.openai cls         layer_11     46.666667
convnext_tiny                    auto        layer_3      45.833333
vit_base_patch16_224             cls         layer_11     44.166667
vit_base_patch16_clip_224.openai mean_tokens layer_11     37.500000
convnext_tiny                    auto        layer_2      22.500000
                                             layer_0      14.166667
vit_base_patch16_224             mean_tokens layer_6      14.166667
vit_base_patch16_clip_224.openai mean_tokens layer_6      11.666667
vit_base_patch16_224             cls         layer_6      10.833333
                                 mean_tokens layer_0       7.500000
vit_base_patch16_clip_224.openai cls         layer_6       6.666667

                                                       gen_avg_margin  \
model_name                       pooling     layer
vit_base_patch16_224             mean_tokens layer_11       -0.015178
vit_base_patch16_clip_224.openai cls         layer_11       -0.007951
convnext_tiny                    auto        layer_3        -0.031299
vit_base_patch16_224             cls         layer_11       -0.010002
vit_base_patch16_clip_224.openai mean_tokens layer_11       -0.015778
convnext_tiny                    auto        layer_2        -0.000222
                                             layer_0        -0.004893
vit_base_patch16_224             mean_tokens layer_6        -0.069697
vit_base_patch16_clip_224.openai mean_tokens layer_6        -0.069563
vit_base_patch16_224             cls         layer_6        -0.017068
                                 mean_tokens layer_0        -0.031433
vit_base_patch16_clip_224.openai cls         layer_6        -0.027223

                                                       human_rdm_spearman  \
model_name                       pooling     layer
vit_base_patch16_224             mean_tokens layer_11            0.338123
vit_base_patch16_clip_224.openai cls         layer_11            0.579635
convnext_tiny                    auto        layer_3             0.297747
vit_base_patch16_224             cls         layer_11            0.263785
vit_base_patch16_clip_224.openai mean_tokens layer_11            0.481256
convnext_tiny                    auto        layer_2             0.377717
                                             layer_0             0.189642
vit_base_patch16_224             mean_tokens layer_6             0.379343
vit_base_patch16_clip_224.openai mean_tokens layer_6             0.387395
vit_base_patch16_224             cls         layer_6             0.297806
                                 mean_tokens layer_0             0.249127
vit_base_patch16_clip_224.openai cls         layer_6             0.125061

                                                       gen_same_concept_accuracy
model_name                       pooling     layer
vit_base_patch16_224             mean_tokens layer_11                  82.500000
vit_base_patch16_clip_224.openai cls         layer_11                  63.333333
convnext_tiny                    auto        layer_3                   80.000000
vit_base_patch16_224             cls         layer_11                  82.500000
vit_base_patch16_clip_224.openai mean_tokens layer_11                  48.333333
convnext_tiny                    auto        layer_2                   39.166667
                                             layer_0                   16.666667
vit_base_patch16_224             mean_tokens layer_6                   23.333333
vit_base_patch16_clip_224.openai mean_tokens layer_6                   18.333333
vit_base_patch16_224             cls         layer_6                   17.500000
                                 mean_tokens layer_0                    9.166667
vit_base_patch16_clip_224.openai cls         layer_6                    7.500000

## Vegetables

In [5]:
# This cell runs the vegetables baseline on the balanced 3-exemplar subset.
# The summary output confirms that the same naturalistic pipeline was applied to vegetables
# after dropping the irregular concepts that break the balanced fold structure.

vegetables_summary = run_naturalistic_baseline(
    category="vegetables",
    device=DEVICE,
    batch_size=BATCH_SIZE,
    seed=SEED,
    output_dir=OUTPUT_DIR,
    dataset_pkl="datasets_peterson.pkl",
    image_root=".",
    required_exemplars=3,
    model_specs=MODEL_SPECS,
)
vegetables_summary

{'category': 'vegetables',
 'chance_accuracy_values': [1.2820512820512822],
 'required_exemplars': 3,
 'split_mode': 'balanced_exemplar_folds',
 'storage_sizes': [78],
 'n_seeds': None,
 'models': ['vit_base_patch16_224::cls',
  'vit_base_patch16_224::mean_tokens',
  'convnext_tiny::auto',
  'vit_base_patch16_clip_224.openai::cls',
  'vit_base_patch16_clip_224.openai::mean_tokens'],
 'sanity_all_pass': True,
 'best_generalization': {'vit_base_patch16_224::cls': {'category': 'vegetables',
   'split_label': 'fold_2',
   'split_seed': 2,
   'split_mode': 'balanced_exemplar_folds',
   'model_name': 'vit_base_patch16_224',
   'pooling': 'cls',
   'layer': 'layer_11',
   'n_stored': 78,
   'n_probe': 39,
   'chance_accuracy': 1.2820512820512822,
   'ident_accuracy': 100.0,
   'ident_avg_target_sim': 0.9971911439579468,
   'ident_avg_margin': 0.05684995040204006,
   'gen_accuracy': 53.84615384615385,
   'gen_avg_target_sim': 0.93566022171443,
   'gen_avg_margin': -0.003939512681418282,
   'gen_avg_retrieved_human_similarity': 0.7235897435897435,
   'gen_avg_human_similarity_regret': 0.0987179487179487,
   'gen_same_concept_accuracy': 74.35897435897436,
   'human_rdm_spearman': 0.30382727361018574,
   'exact_accuracy': 100.0,
   'clean_reextract_accuracy': 100.0,
   'exact_avg_target_sim': 1.0000000450845665,
   'clean_reextract_avg_target_sim': 1.0000000450845665},
  'vit_base_patch16_224::mean_tokens': {'category': 'vegetables',
   'split_label': 'fold_1',
   'split_seed': 1,
   'split_mode': 'balanced_exemplar_folds',
   'model_name': 'vit_base_patch16_224',
   'pooling': 'mean_tokens',
   'layer': 'layer_11',
   'n_stored': 78,
   'n_probe': 39,
   'chance_accuracy': 1.2820512820512822,
   'ident_accuracy': 100.0,
   'ident_avg_target_sim': 0.9959578053642206,
   'ident_avg_margin': 0.10609656886521901,
   'gen_accuracy': 48.717948717948715,
   'gen_avg_target_sim': 0.868456489784156,
   'gen_avg_margin': -0.024580146232097706,
   'gen_avg_retrieved_human_similarity': 0.7423076923076923,
   'gen_avg_human_similarity_regret': 0.08282051282051281,
   'gen_same_concept_accuracy': 82.05128205128204,
   'human_rdm_spearman': 0.3153889234267674,
   'exact_accuracy': 100.0,
   'clean_reextract_accuracy': 100.0,
   'exact_avg_target_sim': 1.0000000343862967,
   'clean_reextract_avg_target_sim': 1.0000000343862967},
  'convnext_tiny::auto': {'category': 'vegetables',
   'split_label': 'fold_0',
   'split_seed': 0,
   'split_mode': 'balanced_exemplar_folds',
   'model_name': 'convnext_tiny',
   'pooling': 'auto',
   'layer': 'layer_3',
   'n_stored': 78,
   'n_probe': 39,
   'chance_accuracy': 1.2820512820512822,
   'ident_accuracy': 100.0,
   'ident_avg_target_sim': 0.9870894331709743,
   'ident_avg_margin': 0.1845539803075839,
   'gen_accuracy': 46.15384615384615,
   'gen_avg_target_sim': 0.7846532128909911,
   'gen_avg_margin': -0.03292104164337099,
   'gen_avg_retrieved_human_similarity': 0.7315384615384615,
   'gen_avg_human_similarity_regret': 0.08846153846153845,
   'gen_same_concept_accuracy': 82.05128205128204,
   'human_rdm_spearman': 0.321495922726537,
   'exact_accuracy': 100.0,
   'clean_reextract_accuracy': 100.0,
   'exact_avg_target_sim': 1.000000036678783,
   'clean_reextract_avg_target_sim': 1.000000036678783},
  'vit_base_patch16_clip_224.openai::cls': {'category': 'vegetables',
   'split_label': 'fold_1',
   'split_seed': 1,
   'split_mode': 'balanced_exemplar_folds',
   'model_name': 'vit_base_patch16_clip_224.openai',
   'pooling': 'cls',
   'layer': 'layer_11',
   'n_stored': 78,
   'n_probe': 39,
   'chance_accuracy': 1.2820512820512822,
   'ident_accuracy': 100.0,
   'ident_avg_target_sim': 0.9568974453411361,
   'ident_avg_margin': 0.14773749288712898,
   'gen_accuracy': 48.717948717948715,
   'gen_avg_target_sim': 0.7921351688350051,
   'gen_avg_margin': -0.01942394021057647,
   'gen_avg_retrieved_human_similarity': 0.7376923076923078,
   'gen_avg_human_similarity_regret': 0.08743589743589744,
   'gen_same_concept_accuracy': 69.23076923076923,
   'human_rdm_spearman': 0.49362566321357754,
   'exact_accuracy': 100.0,
   'clean_reextract_accuracy': 100.0,
   'exact_avg_target_sim': 1.000000022923865,
   'clean_reextract_avg_target_sim': 1.000000022923865},
  'vit_base_patch16_clip_224.openai::mean_tokens': {'category': 'vegetables',
   'split_label': 'fold_0',
   'split_seed': 0,
   'split_mode': 'balanced_exemplar_folds',
   'model_name': 'vit_base_patch16_clip_224.openai',
   'pooling': 'mean_tokens',
   'layer': 'layer_11',
   'n_stored': 78,
   'n_probe': 39,
   'chance_accuracy': 1.2820512820512822,
   'ident_accuracy': 100.0,
   'ident_avg_target_sim': 0.9950337668100837,
   'ident_avg_margin': 0.07330379916459327,
   'gen_accuracy': 41.02564102564102,
   'gen_avg_target_sim': 0.9180276772190809,
   'gen_avg_margin': -0.01012433563471781,
   'gen_avg_retrieved_human_similarity': 0.720911682051282,
   'gen_avg_human_similarity_regret': 0.09908831794871793,
   'gen_same_concept_accuracy': 71.7948717948718,
   'human_rdm_spearman': 0.49228472856998207,
   'exact_accuracy': 100.0,
   'clean_reextract_accuracy': 100.0,
   'exact_avg_target_sim': 1.0000000213955405,
   'clean_reextract_avg_target_sim': 1.0000000213955405}},
 'best_alignment': {'vit_base_patch16_224::cls': {'category': 'vegetables',
   'split_label': 'fold_0',
   'split_seed': 0,
   'split_mode': 'balanced_exemplar_folds',
   'model_name': 'vit_base_patch16_224',
   'pooling': 'cls',
   'layer': 'layer_6',
   'n_stored': 78,
   'n_probe': 39,
   'chance_accuracy': 1.2820512820512822,
   'ident_accuracy': 100.0,
   'ident_avg_target_sim': 0.99569402346804,
   'ident_avg_margin': 0.033881560808922684,
   'gen_accuracy': 23.076923076923077,
   'gen_avg_target_sim': 0.9524861090681236,
   'gen_avg_margin': -0.012788514246577818,
   'gen_avg_retrieved_human_similarity': 0.5212820512820513,
   'gen_avg_human_similarity_regret': 0.29871794871794866,
   'gen_same_concept_accuracy': 38.46153846153847,
   'human_rdm_spearman': 0.3546877856212228,
   'exact_accuracy': 100.0,
   'clean_reextract_accuracy': 100.0,
   'exact_avg_target_sim': 1.0000000313296489,
   'clean_reextract_avg_target_sim': 1.0000000313296489},
  'vit_base_patch16_224::mean_tokens': {'category': 'vegetables',
   'split_label': 'fold_0',
   'split_seed': 0,
   'split_mode': 'balanced_exemplar_folds',
   'model_name': 'vit_base_patch16_224',
   'pooling': 'mean_tokens',
   'layer': 'layer_6',
   'n_stored': 78,
   'n_probe': 39,
   'chance_accuracy': 1.2820512820512822,
   'ident_accuracy': 100.0,
   'ident_avg_target_sim': 0.9929951687041418,
   'ident_avg_margin': 0.17087649035664215,
   'gen_accuracy': 30.76923076923077,
   'gen_avg_target_sim': 0.7955013044165647,
   'gen_avg_margin': -0.03286174540496906,
   'gen_avg_retrieved_human_similarity': 0.5297435897435898,
   'gen_avg_human_similarity_regret': 0.29025641025641025,
   'gen_same_concept_accuracy': 46.15384615384615,
   'human_rdm_spearman': 0.46154232330192874,
   'exact_accuracy': 100.0,
   'clean_reextract_accuracy': 100.0,
   'exact_avg_target_sim': 1.000000022923865,
   'clean_reextract_avg_target_sim': 1.000000022923865},
  'convnext_tiny::auto': {'category': 'vegetables',
   'split_label': 'fold_0',
   'split_seed': 0,
   'split_mode': 'balanced_exemplar_folds',
   'model_name': 'convnext_tiny',
   'pooling': 'auto',
   'layer': 'layer_2',
   'n_stored': 78,
   'n_probe': 39,
   'chance_accuracy': 1.2820512820512822,
   'ident_accuracy': 100.0,
   'ident_avg_target_sim': 0.9999845776786369,
   'ident_avg_margin': 0.0005934934062344754,
   'gen_accuracy': 38.46153846153847,
   'gen_avg_target_sim': 0.9993284283267573,
   'gen_avg_margin': -0.00012931150419108863,
   'gen_avg_retrieved_human_similarity': 0.6371794871794871,
   'gen_avg_human_similarity_regret': 0.18282051282051281,
   'gen_same_concept_accuracy': 53.84615384615385,
   'human_rdm_spearman': 0.36835261169661454,
   'exact_accuracy': 100.0,
   'clean_reextract_accuracy': 100.0,
   'exact_avg_target_sim': 1.0000000397354323,
   'clean_reextract_avg_target_sim': 1.0000000397354323},
  'vit_base_patch16_clip_224.openai::cls': {'category': 'vegetables',
   'split_label': 'fold_0',
   'split_seed': 0,
   'split_mode': 'balanced_exemplar_folds',
   'model_name': 'vit_base_patch16_clip_224.openai',
   'pooling': 'cls',
   'layer': 'layer_11',
   'n_stored': 78,
   'n_probe': 39,
   'chance_accuracy': 1.2820512820512822,
   'ident_accuracy': 100.0,
   'ident_avg_target_sim': 0.9527099789768727,
   'ident_avg_margin': 0.1550131911892248,
   'gen_accuracy': 46.15384615384615,
   'gen_avg_target_sim': 0.8088025031148808,
   'gen_avg_margin': -0.015055125082689774,
   'gen_avg_retrieved_human_similarity': 0.7387179487179486,
   'gen_avg_human_similarity_regret': 0.0812820512820513,
   'gen_same_concept_accuracy': 82.05128205128204,
   'human_rdm_spearman': 0.49362566321357754,
   'exact_accuracy': 100.0,
   'clean_reextract_accuracy': 100.0,
   'exact_avg_target_sim': 1.0000000229238648,
   'clean_reextract_avg_target_sim': 1.0000000229238648},
  'vit_base_patch16_clip_224.openai::mean_tokens': {'category': 'vegetables',
   'split_label': 'fold_0',
   'split_seed': 0,
   'split_mode': 'balanced_exemplar_folds',
   'model_name': 'vit_base_patch16_clip_224.openai',
   'pooling': 'mean_tokens',
   'layer': 'layer_11',
   'n_stored': 78,
   'n_probe': 39,
   'chance_accuracy': 1.2820512820512822,
   'ident_accuracy': 100.0,
   'ident_avg_target_sim': 0.9950337668100837,
   'ident_avg_margin': 0.07330379916459327,
   'gen_accuracy': 41.02564102564102,
   'gen_avg_target_sim': 0.9180276772190809,
   'gen_avg_margin': -0.01012433563471781,
   'gen_avg_retrieved_human_similarity': 0.720911682051282,
   'gen_avg_human_similarity_regret': 0.09908831794871793,
   'gen_same_concept_accuracy': 71.7948717948718,
   'human_rdm_spearman': 0.49228472856998207,
   'exact_accuracy': 100.0,
   'clean_reextract_accuracy': 100.0,
   'exact_avg_target_sim': 1.0000000213955405,
   'clean_reextract_avg_target_sim': 1.0000000213955405}},
 'best_margin': {'vit_base_patch16_224::cls': {'category': 'vegetables',
   'split_label': 'fold_0',
   'split_seed': 0,
   'split_mode': 'balanced_exemplar_folds',
   'model_name': 'vit_base_patch16_224',
   'pooling': 'cls',
   'layer': 'layer_0',
   'n_stored': 78,
   'n_probe': 39,
   'chance_accuracy': 1.2820512820512822,
   'ident_accuracy': 100.0,
   'ident_avg_target_sim': 0.999996876104125,
   'ident_avg_margin': 7.276887033765178e-05,
   'gen_accuracy': 2.564102564102564,
   'gen_avg_target_sim': 0.9997325386611917,
   'gen_avg_margin': -0.00020294771192615654,
   'gen_avg_retrieved_human_similarity': 0.32974358974358975,
   'gen_avg_human_similarity_regret': 0.49025641025641026,
   'gen_same_concept_accuracy': 10.256410256410255,
   'human_rdm_spearman': 0.23028333369635332,
   'exact_accuracy': 100.0,
   'clean_reextract_accuracy': 100.0,
   'exact_avg_target_sim': 1.0000000404995946,
   'clean_reextract_avg_target_sim': 1.0000000404995946},
  'vit_base_patch16_224::mean_tokens': {'category': 'vegetables',
   'split_label': 'fold_2',
   'split_seed': 2,
   'split_mode': 'balanced_exemplar_folds',
   'model_name': 'vit_base_patch16_224',
   'pooling': 'mean_tokens',
   'layer': 'layer_11',
   'n_stored': 78,
   'n_probe': 39,
   'chance_accuracy': 1.2820512820512822,
   'ident_accuracy': 100.0,
   'ident_avg_target_sim': 0.9957645969103489,
   'ident_avg_margin': 0.10184429109994725,
   'gen_accuracy': 43.58974358974359,
   'gen_avg_target_sim': 0.882740887490194,
   'gen_avg_margin': -0.010544280827292578,
   'gen_avg_retrieved_human_similarity': 0.6938461538461538,
   'gen_avg_human_similarity_regret': 0.12846153846153846,
   'gen_same_concept_accuracy': 69.23076923076923,
   'human_rdm_spearman': 0.3153889234267674,
   'exact_accuracy': 100.0,
   'clean_reextract_accuracy': 100.0,
   'exact_avg_target_sim': 1.0000000412637549,
   'clean_reextract_avg_target_sim': 1.0000000412637549},
  'convnext_tiny::auto': {'category': 'vegetables',
   'split_label': 'fold_1',
   'split_seed': 1,
   'split_mode': 'balanced_exemplar_folds',
   'model_name': 'convnext_tiny',
   'pooling': 'auto',
   'layer': 'layer_2',
   'n_stored': 78,
   'n_probe': 39,
   'chance_accuracy': 1.2820512820512822,
   'ident_accuracy': 100.0,
   'ident_avg_target_sim': 0.9999864674514983,
   'ident_avg_margin': 0.0005405002913275569,
   'gen_accuracy': 35.8974358974359,
   'gen_avg_target_sim': 0.9992845868127335,
   'gen_avg_margin': -0.00011326258984182924,
   'gen_avg_retrieved_human_similarity': 0.6120512820512821,
   'gen_avg_human_similarity_regret': 0.21307692307692308,
   'gen_same_concept_accuracy': 53.84615384615385,
   'human_rdm_spearman': 0.36835261169661454,
   'exact_accuracy': 100.0,
   'clean_reextract_accuracy': 100.0,
   'exact_avg_target_sim': 1.0000000351504594,
   'clean_reextract_avg_target_sim': 1.0000000351504594},
  'vit_base_patch16_clip_224.openai::cls': {'category': 'vegetables',
   'split_label': 'fold_0',
   'split_seed': 0,
   'split_mode': 'balanced_exemplar_folds',
   'model_name': 'vit_base_patch16_clip_224.openai',
   'pooling': 'cls',
   'layer': 'layer_0',
   'n_stored': 78,
   'n_probe': 39,
   'chance_accuracy': 1.2820512820512822,
   'ident_accuracy': 100.0,
   'ident_avg_target_sim': 0.9998950408002639,
   'ident_avg_margin': 0.0010888309375988127,
   'gen_accuracy': 2.564102564102564,
   'gen_avg_target_sim': 0.9971469822558416,
   'gen_avg_margin': -0.001703746921622508,
   'gen_avg_retrieved_human_similarity': 0.3558974358974359,
   'gen_avg_human_similarity_regret': 0.4641025641025641,
   'gen_same_concept_accuracy': 20.51282051282051,
   'human_rdm_spearman': 0.3636640444287543,
   'exact_accuracy': 100.0,
   'clean_reextract_accuracy': 100.0,
   'exact_avg_target_sim': 1.0000000404995932,
   'clean_reextract_avg_target_sim': 1.0000000404995932},
  'vit_base_patch16_clip_224.openai::mean_tokens': {'category': 'vegetables',
   'split_label': 'fold_2',
   'split_seed': 2,
   'split_mode': 'balanced_exemplar_folds',
   'model_name': 'vit_base_patch16_clip_224.openai',
   'pooling': 'mean_tokens',
   'layer': 'layer_11',
   'n_stored': 78,
   'n_probe': 39,
   'chance_accuracy': 1.2820512820512822,
   'ident_accuracy': 100.0,
   'ident_avg_target_sim': 0.995167888646771,
   'ident_avg_margin': 0.06951336649702804,
   'gen_accuracy': 35.8974358974359,
   'gen_avg_target_sim': 0.915728908733791,
   'gen_avg_margin': -0.009284444751845143,
   'gen_avg_retrieved_human_similarity': 0.6487179487179485,
   'gen_avg_human_similarity_regret': 0.1735897435897436,
   'gen_same_concept_accuracy': 61.53846153846154,
   'human_rdm_spearman': 0.49228472856998207,
   'exact_accuracy': 100.0,
   'clean_reextract_accuracy': 100.0,
   'exact_avg_target_sim': 1.0000000313296478,
   'clean_reextract_avg_target_sim': 1.0000000313296478}}}

In [6]:
# This table summarizes vegetables in the same format as fruits.
# Interpret the fields exactly the same way as the fruits table.
# Main finding: the fruits pattern replicates here too.
# In particular, late layers lead retrieval and mid layers lead human-alignment scores.

vegetables = pd.read_csv(OUTPUT_DIR / "vegetables_combined.csv")
vegetables.groupby(["model_name", "pooling", "layer"]).agg({
    "ident_accuracy": "mean",
    "gen_accuracy": "mean",
    "gen_avg_margin": "mean",
    "human_rdm_spearman": "mean",
    "gen_same_concept_accuracy": "mean",
}).sort_values("gen_accuracy", ascending=False).head(12)

                                                       ident_accuracy  \
model_name                       pooling     layer
vit_base_patch16_224             cls         layer_11           100.0
                                 mean_tokens layer_11           100.0
convnext_tiny                    auto        layer_3            100.0
vit_base_patch16_clip_224.openai cls         layer_11           100.0
                                 mean_tokens layer_11           100.0
convnext_tiny                    auto        layer_2            100.0
vit_base_patch16_clip_224.openai mean_tokens layer_6            100.0
vit_base_patch16_224             mean_tokens layer_6            100.0
                                 cls         layer_6            100.0
convnext_tiny                    auto        layer_0            100.0
vit_base_patch16_224             mean_tokens layer_0            100.0
vit_base_patch16_clip_224.openai mean_tokens layer_0            100.0

                                                       gen_accuracy  \
model_name                       pooling     layer
vit_base_patch16_224             cls         layer_11     49.572650
                                 mean_tokens layer_11     46.153846
convnext_tiny                    auto        layer_3      45.299145
vit_base_patch16_clip_224.openai cls         layer_11     45.299145
                                 mean_tokens layer_11     39.316239
convnext_tiny                    auto        layer_2      32.478632
vit_base_patch16_clip_224.openai mean_tokens layer_6      26.495726
vit_base_patch16_224             mean_tokens layer_6      23.931624
                                 cls         layer_6      23.076923
convnext_tiny                    auto        layer_0       9.401709
vit_base_patch16_224             mean_tokens layer_0       9.401709
vit_base_patch16_clip_224.openai mean_tokens layer_0       8.547009

                                                       gen_avg_margin  \
model_name                       pooling     layer
vit_base_patch16_224             cls         layer_11       -0.007381
                                 mean_tokens layer_11       -0.016580
convnext_tiny                    auto        layer_3        -0.033458
vit_base_patch16_clip_224.openai cls         layer_11       -0.017313
                                 mean_tokens layer_11       -0.010555
convnext_tiny                    auto        layer_2        -0.000135
vit_base_patch16_clip_224.openai mean_tokens layer_6        -0.034765
vit_base_patch16_224             mean_tokens layer_6        -0.037967
                                 cls         layer_6        -0.012857
convnext_tiny                    auto        layer_0        -0.004217
vit_base_patch16_224             mean_tokens layer_0        -0.029090
vit_base_patch16_clip_224.openai mean_tokens layer_0        -0.060223

                                                       human_rdm_spearman  \
model_name                       pooling     layer
vit_base_patch16_224             cls         layer_11            0.303827
                                 mean_tokens layer_11            0.315389
convnext_tiny                    auto        layer_3             0.321496
vit_base_patch16_clip_224.openai cls         layer_11            0.493626
                                 mean_tokens layer_11            0.492285
convnext_tiny                    auto        layer_2             0.368353
vit_base_patch16_clip_224.openai mean_tokens layer_6             0.460097
vit_base_patch16_224             mean_tokens layer_6             0.461542
                                 cls         layer_6             0.354688
convnext_tiny                    auto        layer_0             0.284686
vit_base_patch16_224             mean_tokens layer_0             0.327619
vit_base_patch16_clip_224.openai mean_tokens layer_0             0.374462

                                                       gen_same_concept_accuracy
model_name                       pooling     layer
vit_base_patch16_224             cls         layer_11                  80.341880
                                 mean_tokens layer_11                  77.777778
convnext_tiny                    auto        layer_3                   82.905983
vit_base_patch16_clip_224.openai cls         layer_11                  72.649573
                                 mean_tokens layer_11                  69.230769
convnext_tiny                    auto        layer_2                   50.427350
vit_base_patch16_clip_224.openai mean_tokens layer_6                   48.717949
vit_base_patch16_224             mean_tokens layer_6                   42.735043
                                 cls         layer_6                   36.752137
convnext_tiny                    auto        layer_0                   15.384615
vit_base_patch16_224             mean_tokens layer_0                   15.384615
vit_base_patch16_clip_224.openai mean_tokens layer_0                   14.529915

## Animals

In [7]:
# This cell runs the animals baseline using random storage curves instead of exemplar folds.
# Animals does not have the same visible 3-exemplar concept structure as fruits/vegetables,
# so this category is evaluated across multiple random stored-set sizes and seeds.

animals_summary = run_naturalistic_baseline(
    category="animals",
    device=DEVICE,
    batch_size=BATCH_SIZE,
    seed=SEED,
    output_dir=OUTPUT_DIR,
    dataset_pkl="datasets_peterson.pkl",
    image_root=".",
    split_mode="random_storage_curve",
    storage_sizes=[40, 80],
    n_seeds=5,
    model_specs=MODEL_SPECS,
)
animals_summary

{'category': 'animals',
 'chance_accuracy_values': [1.25, 2.5],
 'required_exemplars': None,
 'split_mode': 'random_storage_curve',
 'storage_sizes': [40, 80],
 'n_seeds': 5,
 'models': ['vit_base_patch16_224::cls',
  'vit_base_patch16_224::mean_tokens',
  'convnext_tiny::auto',
  'vit_base_patch16_clip_224.openai::cls',
  'vit_base_patch16_clip_224.openai::mean_tokens'],
 'sanity_all_pass': True,
 'best_generalization': {'vit_base_patch16_224::cls': {'category': 'animals',
   'split_label': 'stored_80_seed_2',
   'split_seed': 2,
   'split_mode': 'random_storage_curve',
   'model_name': 'vit_base_patch16_224',
   'pooling': 'cls',
   'layer': 'layer_11',
   'n_stored': 80,
   'n_probe': 40,
   'chance_accuracy': 1.25,
   'ident_accuracy': 100.0,
   'ident_avg_target_sim': 0.9958626759660654,
   'ident_avg_margin': 0.04188455122482477,
   'gen_accuracy': 70.0,
   'gen_avg_target_sim': 0.9464424723121064,
   'gen_avg_margin': 0.013994442624434167,
   'gen_avg_retrieved_human_similarity': 0.8547499999999999,
   'gen_avg_human_similarity_regret': 0.04225000000000002,
   'gen_same_concept_accuracy': nan,
   'human_rdm_spearman': 0.10526401895764113,
   'exact_accuracy': 100.0,
   'clean_reextract_accuracy': 100.0,
   'exact_avg_target_sim': 1.0000000372519042,
   'clean_reextract_avg_target_sim': 1.0000000372519042},
  'vit_base_patch16_224::mean_tokens': {'category': 'animals',
   'split_label': 'stored_80_seed_1',
   'split_seed': 1,
   'split_mode': 'random_storage_curve',
   'model_name': 'vit_base_patch16_224',
   'pooling': 'mean_tokens',
   'layer': 'layer_11',
   'n_stored': 80,
   'n_probe': 40,
   'chance_accuracy': 1.25,
   'ident_accuracy': 100.0,
   'ident_avg_target_sim': 0.9943620627514622,
   'ident_avg_margin': 0.07814575320154471,
   'gen_accuracy': 65.0,
   'gen_avg_target_sim': 0.8892790617883772,
   'gen_avg_margin': 0.019725684309200804,
   'gen_avg_retrieved_human_similarity': 0.85725,
   'gen_avg_human_similarity_regret': 0.05300000000000001,
   'gen_same_concept_accuracy': nan,
   'human_rdm_spearman': 0.18776039648550022,
   'exact_accuracy': 100.0,
   'clean_reextract_accuracy': 100.0,
   'exact_avg_target_sim': 1.0000000335266135,
   'clean_reextract_avg_target_sim': 1.0000000335266135},
  'convnext_tiny::auto': {'category': 'animals',
   'split_label': 'stored_80_seed_0',
   'split_seed': 0,
   'split_mode': 'random_storage_curve',
   'model_name': 'convnext_tiny',
   'pooling': 'auto',
   'layer': 'layer_3',
   'n_stored': 80,
   'n_probe': 40,
   'chance_accuracy': 1.25,
   'ident_accuracy': 100.0,
   'ident_avg_target_sim': 0.9867498259784842,
   'ident_avg_margin': 0.1648423037510559,
   'gen_accuracy': 62.5,
   'gen_avg_target_sim': 0.7891207184344433,
   'gen_avg_margin': 0.05541337883993121,
   'gen_avg_retrieved_human_similarity': 0.8537500000000001,
   'gen_avg_human_similarity_regret': 0.05700000000000001,
   'gen_same_concept_accuracy': nan,
   'human_rdm_spearman': 0.04647035699842218,
   'exact_accuracy': 100.0,
   'clean_reextract_accuracy': 100.0,
   'exact_avg_target_sim': 1.0000000245859173,
   'clean_reextract_avg_target_sim': 1.0000000245859173},
  'vit_base_patch16_clip_224.openai::cls': {'category': 'animals',
   'split_label': 'stored_40_seed_4',
   'split_seed': 4,
   'split_mode': 'random_storage_curve',
   'model_name': 'vit_base_patch16_clip_224.openai',
   'pooling': 'cls',
   'layer': 'layer_11',
   'n_stored': 40,
   'n_probe': 80,
   'chance_accuracy': 2.5,
   'ident_accuracy': 100.0,
   'ident_avg_target_sim': 0.9433984971503477,
   'ident_avg_margin': 0.17583633232972692,
   'gen_accuracy': 63.74999999999999,
   'gen_avg_target_sim': 0.7588488199709423,
   'gen_avg_margin': 0.020679886231139494,
   'gen_avg_retrieved_human_similarity': 0.8265,
   'gen_avg_human_similarity_regret': 0.039875,
   'gen_same_concept_accuracy': nan,
   'human_rdm_spearman': 0.5496510499729654,
   'exact_accuracy': 100.0,
   'clean_reextract_accuracy': 100.0,
   'exact_avg_target_sim': 1.0000000268210925,
   'clean_reextract_avg_target_sim': 1.0000000268210925},
  'vit_base_patch16_clip_224.openai::mean_tokens': {'category': 'animals',
   'split_label': 'stored_40_seed_2',
   'split_seed': 2,
   'split_mode': 'random_storage_curve',
   'model_name': 'vit_base_patch16_clip_224.openai',
   'pooling': 'mean_tokens',
   'layer': 'layer_11',
   'n_stored': 40,
   'n_probe': 80,
   'chance_accuracy': 2.5,
   'ident_accuracy': 100.0,
   'ident_avg_target_sim': 0.9917519953677474,
   'ident_avg_margin': 0.07290146260384964,
   'gen_accuracy': 51.24999999999999,
   'gen_avg_target_sim': 0.8922227495228864,
   'gen_avg_margin': -0.009253182205401929,
   'gen_avg_retrieved_human_similarity': 0.7205937499999999,
   'gen_avg_human_similarity_regret': 0.11100000000000002,
   'gen_same_concept_accuracy': nan,
   'human_rdm_spearman': 0.36098498217834274,
   'exact_accuracy': 100.0,
   'clean_reextract_accuracy': 100.0,
   'exact_avg_target_sim': 1.0000000327815557,
   'clean_reextract_avg_target_sim': 1.0000000327815557}},
 'best_alignment': {'vit_base_patch16_224::cls': {'category': 'animals',
   'split_label': 'stored_40_seed_0',
   'split_seed': 0,
   'split_mode': 'random_storage_curve',
   'model_name': 'vit_base_patch16_224',
   'pooling': 'cls',
   'layer': 'layer_6',
   'n_stored': 40,
   'n_probe': 80,
   'chance_accuracy': 2.5,
   'ident_accuracy': 100.0,
   'ident_avg_target_sim': 0.9882140275054475,
   'ident_avg_margin': 0.030583416463087154,
   'gen_accuracy': 22.5,
   'gen_avg_target_sim': 0.9508314466407939,
   'gen_avg_margin': -0.012067791438864625,
   'gen_avg_retrieved_human_similarity': 0.5262499999999999,
   'gen_avg_human_similarity_regret': 0.32299999999999995,
   'gen_same_concept_accuracy': nan,
   'human_rdm_spearman': 0.28781941301942127,
   'exact_accuracy': 100.0,
   'clean_reextract_accuracy': 100.0,
   'exact_avg_target_sim': 1.000000017880394,
   'clean_reextract_avg_target_sim': 1.000000017880394},
  'vit_base_patch16_224::mean_tokens': {'category': 'animals',
   'split_label': 'stored_40_seed_0',
   'split_seed': 0,
   'split_mode': 'random_storage_curve',
   'model_name': 'vit_base_patch16_224',
   'pooling': 'mean_tokens',
   'layer': 'layer_6',
   'n_stored': 40,
   'n_probe': 80,
   'chance_accuracy': 2.5,
   'ident_accuracy': 100.0,
   'ident_avg_target_sim': 0.9848514893253663,
   'ident_avg_margin': 0.14100558267466384,
   'gen_accuracy': 23.75,
   'gen_avg_target_sim': 0.8043249170439513,
   'gen_avg_margin': -0.037301912031835055,
   'gen_avg_retrieved_human_similarity': 0.52,
   'gen_avg_human_similarity_regret': 0.32925,
   'gen_same_concept_accuracy': nan,
   'human_rdm_spearman': 0.4234278298587324,
   'exact_accuracy': 100.0,
   'clean_reextract_accuracy': 100.0,
   'exact_avg_target_sim': 1.0000000268210922,
   'clean_reextract_avg_target_sim': 1.0000000268210922},
  'convnext_tiny::auto': {'category': 'animals',
   'split_label': 'stored_40_seed_0',
   'split_seed': 0,
   'split_mode': 'random_storage_curve',
   'model_name': 'convnext_tiny',
   'pooling': 'auto',
   'layer': 'layer_2',
   'n_stored': 40,
   'n_probe': 80,
   'chance_accuracy': 2.5,
   'ident_accuracy': 100.0,
   'ident_avg_target_sim': 0.9999692097279415,
   'ident_avg_margin': 0.0003932833902463795,
   'gen_accuracy': 32.5,
   'gen_avg_target_sim': 0.9994804598188128,
   'gen_avg_margin': -8.441731503265188e-05,
   'gen_avg_retrieved_human_similarity': 0.571,
   'gen_avg_human_similarity_regret': 0.27825,
   'gen_same_concept_accuracy': nan,
   'human_rdm_spearman': 0.3009191900846657,
   'exact_accuracy': 100.0,
   'clean_reextract_accuracy': 100.0,
   'exact_avg_target_sim': 1.0000000536431828,
   'clean_reextract_avg_target_sim': 1.0000000536431828},
  'vit_base_patch16_clip_224.openai::cls': {'category': 'animals',
   'split_label': 'stored_40_seed_0',
   'split_seed': 0,
   'split_mode': 'random_storage_curve',
   'model_name': 'vit_base_patch16_clip_224.openai',
   'pooling': 'cls',
   'layer': 'layer_11',
   'n_stored': 40,
   'n_probe': 80,
   'chance_accuracy': 2.5,
   'ident_accuracy': 100.0,
   'ident_avg_target_sim': 0.9434048461949669,
   'ident_avg_margin': 0.18128232819883322,
   'gen_accuracy': 56.25,
   'gen_avg_target_sim': 0.7425292316254455,
   'gen_avg_margin': 0.011923207756670284,
   'gen_avg_retrieved_human_similarity': 0.770125,
   'gen_avg_human_similarity_regret': 0.079125,
   'gen_same_concept_accuracy': nan,
   'human_rdm_spearman': 0.5496510499729654,
   'exact_accuracy': 100.0,
   'clean_reextract_accuracy': 100.0,
   'exact_avg_target_sim': 1.0000000208606272,
   'clean_reextract_avg_target_sim': 1.0000000208606272},
  'vit_base_patch16_clip_224.openai::mean_tokens': {'category': 'animals',
   'split_label': 'stored_40_seed_0',
   'split_seed': 0,
   'split_mode': 'random_storage_curve',
   'model_name': 'vit_base_patch16_clip_224.openai',
   'pooling': 'mean_tokens',
   'layer': 'layer_6',
   'n_stored': 40,
   'n_probe': 80,
   'chance_accuracy': 2.5,
   'ident_accuracy': 100.0,
   'ident_avg_target_sim': 0.979347423725551,
   'ident_avg_margin': 0.11821076548927956,
   'gen_accuracy': 27.500000000000004,
   'gen_avg_target_sim': 0.8139880659854668,
   'gen_avg_margin': -0.03697425717888314,
   'gen_avg_retrieved_human_similarity': 0.48687500000000006,
   'gen_avg_human_similarity_regret': 0.362375,
   'gen_same_concept_accuracy': nan,
   'human_rdm_spearman': 0.3760547736602929,
   'exact_accuracy': 100.0,
   'clean_reextract_accuracy': 100.0,
   'exact_avg_target_sim': 1.000000026821091,
   'clean_reextract_avg_target_sim': 1.000000026821091}},
 'best_margin': {'vit_base_patch16_224::cls': {'category': 'animals',
   'split_label': 'stored_80_seed_2',
   'split_seed': 2,
   'split_mode': 'random_storage_curve',
   'model_name': 'vit_base_patch16_224',
   'pooling': 'cls',
   'layer': 'layer_11',
   'n_stored': 80,
   'n_probe': 40,
   'chance_accuracy': 1.25,
   'ident_accuracy': 100.0,
   'ident_avg_target_sim': 0.9958626759660654,
   'ident_avg_margin': 0.04188455122482477,
   'gen_accuracy': 70.0,
   'gen_avg_target_sim': 0.9464424723121064,
   'gen_avg_margin': 0.013994442624434167,
   'gen_avg_retrieved_human_similarity': 0.8547499999999999,
   'gen_avg_human_similarity_regret': 0.04225000000000002,
   'gen_same_concept_accuracy': nan,
   'human_rdm_spearman': 0.10526401895764113,
   'exact_accuracy': 100.0,
   'clean_reextract_accuracy': 100.0,
   'exact_avg_target_sim': 1.0000000372519042,
   'clean_reextract_avg_target_sim': 1.0000000372519042},
  'vit_base_patch16_224::mean_tokens': {'category': 'animals',
   'split_label': 'stored_80_seed_2',
   'split_seed': 2,
   'split_mode': 'random_storage_curve',
   'model_name': 'vit_base_patch16_224',
   'pooling': 'mean_tokens',
   'layer': 'layer_11',
   'n_stored': 80,
   'n_probe': 40,
   'chance_accuracy': 1.25,
   'ident_accuracy': 100.0,
   'ident_avg_target_sim': 0.9942057332263697,
   'ident_avg_margin': 0.07955898658506103,
   'gen_accuracy': 62.5,
   'gen_avg_target_sim': 0.8991979193482227,
   'gen_avg_margin': 0.030505429894001262,
   'gen_avg_retrieved_human_similarity': 0.83025,
   'gen_avg_human_similarity_regret': 0.06675000000000002,
   'gen_same_concept_accuracy': nan,
   'human_rdm_spearman': 0.18776039648550022,
   'exact_accuracy': 100.0,
   'clean_reextract_accuracy': 100.0,
   'exact_avg_target_sim': 1.0000000320364975,
   'clean_reextract_avg_target_sim': 1.0000000320364975},
  'convnext_tiny::auto': {'category': 'animals',
   'split_label': 'stored_80_seed_1',
   'split_seed': 1,
   'split_mode': 'random_storage_curve',
   'model_name': 'convnext_tiny',
   'pooling': 'auto',
   'layer': 'layer_3',
   'n_stored': 80,
   'n_probe': 40,
   'chance_accuracy': 1.25,
   'ident_accuracy': 100.0,
   'ident_avg_target_sim': 0.9851057404418034,
   'ident_avg_margin': 0.1561636049226842,
   'gen_accuracy': 62.5,
   'gen_avg_target_sim': 0.7887490758321487,
   'gen_avg_margin': 0.055413708812304806,
   'gen_avg_retrieved_human_similarity': 0.8477499999999999,
   'gen_avg_human_similarity_regret': 0.0625,
   'gen_same_concept_accuracy': nan,
   'human_rdm_spearman': 0.04647035699842218,
   'exact_accuracy': 100.0,
   'clean_reextract_accuracy': 100.0,
   'exact_avg_target_sim': 1.000000028311208,
   'clean_reextract_avg_target_sim': 1.000000028311208},
  'vit_base_patch16_clip_224.openai::cls': {'category': 'animals',
   'split_label': 'stored_40_seed_3',
   'split_seed': 3,
   'split_mode': 'random_storage_curve',
   'model_name': 'vit_base_patch16_clip_224.openai',
   'pooling': 'cls',
   'layer': 'layer_11',
   'n_stored': 40,
   'n_probe': 80,
   'chance_accuracy': 2.5,
   'ident_accuracy': 100.0,
   'ident_avg_target_sim': 0.9394473522092074,
   'ident_avg_margin': 0.19425690475340648,
   'gen_accuracy': 61.25000000000001,
   'gen_avg_target_sim': 0.7602490226528704,
   'gen_avg_margin': 0.037688366865300825,
   'gen_avg_retrieved_human_similarity': 0.8059999999999998,
   'gen_avg_human_similarity_regret': 0.050124999999999996,
   'gen_same_concept_accuracy': nan,
   'human_rdm_spearman': 0.5496510499729654,
   'exact_accuracy': 100.0,
   'clean_reextract_accuracy': 100.0,
   'exact_avg_target_sim': 1.0000000298013245,
   'clean_reextract_avg_target_sim': 1.0000000298013245},
  'vit_base_patch16_clip_224.openai::mean_tokens': {'category': 'animals',
   'split_label': 'stored_40_seed_0',
   'split_seed': 0,
   'split_mode': 'random_storage_curve',
   'model_name': 'vit_base_patch16_clip_224.openai',
   'pooling': 'mean_tokens',
   'layer': 'layer_11',
   'n_stored': 40,
   'n_probe': 80,
   'chance_accuracy': 2.5,
   'ident_accuracy': 100.0,
   'ident_avg_target_sim': 0.9929562998916104,
   'ident_avg_margin': 0.07871582092050436,
   'gen_accuracy': 48.75,
   'gen_avg_target_sim': 0.8945858115380597,
   'gen_avg_margin': -0.0012482398366107593,
   'gen_avg_retrieved_human_similarity': 0.7152499999999999,
   'gen_avg_human_similarity_regret': 0.13399999999999998,
   'gen_same_concept_accuracy': nan,
   'human_rdm_spearman': 0.36098498217834274,
   'exact_accuracy': 100.0,
   'clean_reextract_accuracy': 100.0,
   'exact_avg_target_sim': 1.0000000372519042,
   'clean_reextract_avg_target_sim': 1.0000000372519042}}}

In [8]:
# This table summarizes the animals benchmark by model, pooling, layer, and n_stored.
# Rows: one representation choice plus one stored-set size.
# Extra animal-specific fields:
# - n_stored: how many images were put in memory for that random split
# - gen_avg_retrieved_human_similarity: average human similarity of the retrieved item
# - gen_avg_human_similarity_regret: how much human similarity was lost relative to the best target
# Main finding: animals gives the strongest retrieval regime in the project.
# It also shows that late-layer retrieval can become positively separated from competitors.

animals = pd.read_csv(OUTPUT_DIR / "animals_combined.csv")
animals.groupby(["model_name", "pooling", "layer", "n_stored"]).agg({
    "ident_accuracy": "mean",
    "gen_accuracy": "mean",
    "gen_avg_margin": "mean",
    "human_rdm_spearman": "mean",
    "gen_avg_retrieved_human_similarity": "mean",
    "gen_avg_human_similarity_regret": "mean",
}).sort_values("gen_accuracy", ascending=False).head(12)

                                                                ident_accuracy  \
model_name                       pooling     layer    n_stored
vit_base_patch16_224             cls         layer_11 80                 100.0
                                 mean_tokens layer_11 80                 100.0
convnext_tiny                    auto        layer_3  80                 100.0
vit_base_patch16_clip_224.openai cls         layer_11 40                 100.0
                                                      80                 100.0
vit_base_patch16_224             cls         layer_11 40                 100.0
convnext_tiny                    auto        layer_3  40                 100.0
vit_base_patch16_224             mean_tokens layer_11 40                 100.0
vit_base_patch16_clip_224.openai mean_tokens layer_11 40                 100.0
                                                      80                 100.0
convnext_tiny                    auto        layer_2  40                 100.0
                                                      80                 100.0

                                                                gen_accuracy  \
model_name                       pooling     layer    n_stored
vit_base_patch16_224             cls         layer_11 80               63.00
                                 mean_tokens layer_11 80               57.50
convnext_tiny                    auto        layer_3  80               57.50
vit_base_patch16_clip_224.openai cls         layer_11 40               56.75
                                                      80               53.00
vit_base_patch16_224             cls         layer_11 40               52.75
convnext_tiny                    auto        layer_3  40               51.00
vit_base_patch16_224             mean_tokens layer_11 40               50.25
vit_base_patch16_clip_224.openai mean_tokens layer_11 40               46.75
                                                      80               42.00
convnext_tiny                    auto        layer_2  40               32.00
                                                      80               27.50

                                                                gen_avg_margin  \
model_name                       pooling     layer    n_stored
vit_base_patch16_224             cls         layer_11 80              0.010480
                                 mean_tokens layer_11 80              0.017868
convnext_tiny                    auto        layer_3  80              0.044627
vit_base_patch16_clip_224.openai cls         layer_11 40              0.012405
                                                      80              0.007916
vit_base_patch16_224             cls         layer_11 40              0.006301
convnext_tiny                    auto        layer_3  40              0.028005
vit_base_patch16_224             mean_tokens layer_11 40              0.012614
vit_base_patch16_clip_224.openai mean_tokens layer_11 40             -0.004531
                                                      80             -0.009058
convnext_tiny                    auto        layer_2  40             -0.000088
                                                      80             -0.000091

                                                                human_rdm_spearman  \
model_name                       pooling     layer    n_stored
vit_base_patch16_224             cls         layer_11 80                  0.105264
                                 mean_tokens layer_11 80                  0.187760
convnext_tiny                    auto        layer_3  80                  0.046470
vit_base_patch16_clip_224.openai cls         layer_11 40                  0.549651
                                                      80                  0.549651
vit_base_patch16_224             cls         layer_11 40                  0.105264
convnext_tiny                    auto        layer_3  40                  0.046470
vit_base_patch16_224             mean_tokens layer_11 40                  0.187760
vit_base_patch16_clip_224.openai mean_tokens layer_11 40                  0.360985
                                                      80                  0.360985
convnext_tiny                    auto        layer_2  40                  0.300919
                                                      80                  0.300919

                                                                gen_avg_retrieved_human_similarity  \
model_name                       pooling     layer    n_stored
vit_base_patch16_224             cls         layer_11 80                                  0.867800
                                 mean_tokens layer_11 80                                  0.852950
convnext_tiny                    auto        layer_3  80                                  0.845800
vit_base_patch16_clip_224.openai cls         layer_11 40                                  0.781787
                                                      80                                  0.869100
vit_base_patch16_224             cls         layer_11 40                                  0.735325
convnext_tiny                    auto        layer_3  40                                  0.712300
vit_base_patch16_224             mean_tokens layer_11 40                                  0.727400
vit_base_patch16_clip_224.openai mean_tokens layer_11 40                                  0.708263
                                                      80                                  0.763400
convnext_tiny                    auto        layer_2  40                                  0.610175
                                                      80                                  0.662400

                                                                gen_avg_human_similarity_regret
model_name                       pooling     layer    n_stored
vit_base_patch16_224             cls         layer_11 80                               0.040650
                                 mean_tokens layer_11 80                               0.055500
convnext_tiny                    auto        layer_3  80                               0.062650
vit_base_patch16_clip_224.openai cls         layer_11 40                               0.061075
                                                      80                               0.039350
vit_base_patch16_224             cls         layer_11 40                               0.107537
convnext_tiny                    auto        layer_3  40                               0.130562
vit_base_patch16_224             mean_tokens layer_11 40                               0.115462
vit_base_patch16_clip_224.openai mean_tokens layer_11 40                               0.134600
                                                      80                               0.145050
convnext_tiny                    auto        layer_2  40                               0.232687
                                                      80                               0.246050

## Integrity And Cross-Category Summary

In [9]:
# This JSON output is a dataset integrity check.
# It confirms that the Peterson filenames match the local image folders and records category sizes,
# image dimensions, and any filtering decisions used to build the naturalistic tasks.

integrity = json.loads((OUTPUT_DIR / "dataset_integrity.json").read_text())
integrity

{'animals': {'category': 'animals',
  'n_images': 120,
  'matrix_shape': [120, 120],
  'is_symmetric': True,
  'diag_mean': 1.0,
  'missing_on_disk': [],
  'extra_on_disk': [],
  'n_concepts': 1,
  'concept_histogram': {'stim-': 120},
  'image_size': [300, 300],
  'required_exemplars': None,
  'dropped_concepts': []},
 'fruits': {'category': 'fruits',
  'n_images': 120,
  'matrix_shape': [120, 120],
  'is_symmetric': True,
  'diag_mean': 1.0,
  'missing_on_disk': [],
  'extra_on_disk': [],
  'n_concepts': 40,
  'concept_histogram': {'ackee': 3,
   'apple': 3,
   'apricot': 3,
   'atemoya': 3,
   'babaco': 3,
   'bacuri': 3,
   'banana': 3,
   'blackberry': 3,
   'blueberry': 3,
   'cantaloupe': 3,
   'carambola': 3,
   'cherry': 3,
   'coconut': 3,
   'cranberry': 3,
   'date': 3,
   'deadmansfinger': 3,
   'dragonfruit': 3,
   'durian': 3,
   'fig': 3,
   'grape': 3,
   'guava': 3,
   'kiwi': 3,
   'lemon': 3,
   'lime': 3,
   'lychee': 3,
   'mango': 3,
   'orange': 3,
   'papaya': 3,
   'passionfruit': 3,
   'peach': 3,
   'pear': 3,
   'persimmon': 3,
   'pineapple': 3,
   'pineberry': 3,
   'plum': 3,
   'pomegranate': 3,
   'pomelo': 3,
   'raspberry': 3,
   'strawberry': 3,
   'watermelon': 3},
  'image_size': [500, 500],
  'required_exemplars': None,
  'dropped_concepts': []},
 'vegetables': {'category': 'vegetables',
  'n_images': 120,
  'matrix_shape': [120, 120],
  'is_symmetric': True,
  'diag_mean': 1.0,
  'missing_on_disk': [],
  'extra_on_disk': [],
  'n_concepts': 41,
  'concept_histogram': {'amaranth': 3,
   'artichoke': 3,
   'arugula': 3,
   'asparagus': 3,
   'beetroot': 3,
   'bellpepper': 3,
   'broccoli': 3,
   'brusselssprouts': 3,
   'cabbage': 3,
   'carrot': 3,
   'catsear': 3,
   'cauliflower': 3,
   'celery': 3,
   'celtuce': 3,
   'chillipeppers': 3,
   'chives': 3,
   'corn': 3,
   'cucumber': 3,
   'daikon': 3,
   'eggplant': 3,
   'ginger': 3,
   'leeks': 3,
   'lettuce': 3,
   'luffa': 3,
   'pea': 3,
   'potatoes': 3,
   'pumpkin': 3,
   'radicchio': 3,
   'redonions': 3,
   'redskinpotato': 3,
   'redswanbean': 3,
   'rhubarb': 3,
   'rutabaga': 3,
   'salsify': 3,
   'seaweed': 3,
   'taisoi': 1,
   'tatsoi': 2,
   'thaieggplant': 3,
   'tomato': 3,
   'wintersquash': 3,
   'yellowonion': 3},
  'image_size': [500, 500],
  'required_exemplars': None,
  'dropped_concepts': []}}

In [10]:
# This cross-category table is sorted by generalization accuracy.
# Rows: the top-performing representation choices within fruits, vegetables, and animals.
# Key fields:
# - category: dataset category being summarized
# - model_name / pooling / layer: representation choice
# - gen_accuracy: top retrieval performance on the human-similarity task
# - human_rdm_spearman: human-alignment score for that same row
# Main finding: animals is the strongest retrieval category, while the late-layer retrieval pattern
# replicates across all three naturalistic categories.

comparison = pd.read_csv(OUTPUT_DIR / "animals_vs_fruits_vs_vegetables_summary.csv")
comparison.sort_values(["category", "gen_accuracy"], ascending=[True, False]).head(18)

,category,model_name,pooling,layer,ident_accuracy,gen_accuracy,gen_avg_margin,gen_avg_retrieved_human_similarity,gen_avg_human_similarity_regret,gen_same_concept_accuracy,human_rdm_spearman,chance_accuracy
31,animals,vit_base_patch16_224,cls,layer_11,100.000,57.875000,0.008390,0.801563,0.074094,NaN,0.105265,1.875
40,animals,vit_base_patch16_clip_224.openai,cls,layer_11,100.000,54.875000,0.010161,0.825444,0.050213,NaN,0.549651,1.875
38,animals,convnext_tiny,auto,layer_3,100.000,54.250000,0.036316,0.779050,0.096606,NaN,0.046470,1.875
34,animals,vit_base_patch16_224,mean_tokens,layer_11,100.000,53.875000,0.015241,0.790175,0.085481,NaN,0.187760,1.875
43,animals,vit_base_patch16_clip_224.openai,mean_tokens,layer_11,100.000,44.375000,-0.006795,0.735831,0.139825,NaN,0.360985,1.875
37,animals,convnext_tiny,auto,layer_2,100.000,29.750000,-0.000090,0.636288,0.239369,NaN,0.300918,1.875
35,animals,vit_base_patch16_224,mean_tokens,layer_6,100.000,20.875000,-0.047784,0.538806,0.336850,NaN,0.423428,1.875
44,animals,vit_base_patch16_clip_224.openai,mean_tokens,layer_6,100.000,20.750000,-0.051145,0.514306,0.361350,NaN,0.376055,1.875
32,animals,vit_base_patch16_224,cls,layer_6,99.500,12.500000,-0.017135,0.489553,0.386103,NaN,0.287819,1.875
42,animals,vit_base_patch16_clip_224.openai,mean_tokens,layer_0,100.000,7.375000,-0.080863,0.344681,0.530975,NaN,0.168027,1.875
36,animals,convnext_tiny,auto,layer_0,79.125,6.250000,-0.004605,0.339066,0.536591,NaN,0.175832,1.875
33,animals,vit_base_patch16_224,mean_tokens,layer_0,100.000,5.750000,-0.033336,0.329800,0.545856,NaN,0.197562,1.875
39,animals,vit_base_patch16_clip_224.openai,cls,layer_0,99.500,5.125000,-0.002436,0.288575,0.587081,NaN,0.142852,1.875
30,animals,vit_base_patch16_224,cls,layer_0,100.000,3.750000,-0.000174,0.273041,0.602616,NaN,0.143548,1.875
41,animals,vit_base_patch16_clip_224.openai,cls,layer_6,15.750,3.500000,-0.040566,0.298937,0.576719,NaN,0.090579,1.875
4,fruits,vit_base_patch16_224,mean_tokens,layer_11,100.000,48.333333,-0.015178,0.701981,0.105472,82.500000,0.338124,1.250
10,fruits,vit_base_patch16_clip_224.openai,cls,layer_11,100.000,46.666667,-0.007951,0.691361,0.116093,63.333333,0.579635,1.250
8,fruits,convnext_tiny,auto,layer_3,100.000,45.833333,-0.031299,0.703185,0.104269,80.000000,0.297746,1.250

- *Adding noise on the decision process*: After calculating the distances, add noise to the distance measures. Possibly trying out DAM.
- Ways to distrupt the identification process: Black out big chunks of the image. Partial input pattern. Try different approachs to image warping.

In [11]:
# This cross-category table is sorted by human_rdm_spearman instead of generalization accuracy.
# It answers a different question: which rows are most human-like geometrically, even if they
# are not the very best retrieval rows.
# Main finding: the best alignment rows are usually different from the best retrieval rows,
# which is the core late-layer retrieval vs mid-layer alignment split in this project.

comparison.sort_values(["category", "human_rdm_spearman"], ascending=[True, False]).head(18)

,category,model_name,pooling,layer,ident_accuracy,gen_accuracy,gen_avg_margin,gen_avg_retrieved_human_similarity,gen_avg_human_similarity_regret,gen_same_concept_accuracy,human_rdm_spearman,chance_accuracy
40,animals,vit_base_patch16_clip_224.openai,cls,layer_11,100.000,54.875000,0.010161,0.825444,0.050213,NaN,0.549651,1.875
35,animals,vit_base_patch16_224,mean_tokens,layer_6,100.000,20.875000,-0.047784,0.538806,0.336850,NaN,0.423428,1.875
44,animals,vit_base_patch16_clip_224.openai,mean_tokens,layer_6,100.000,20.750000,-0.051145,0.514306,0.361350,NaN,0.376055,1.875
43,animals,vit_base_patch16_clip_224.openai,mean_tokens,layer_11,100.000,44.375000,-0.006795,0.735831,0.139825,NaN,0.360985,1.875
37,animals,convnext_tiny,auto,layer_2,100.000,29.750000,-0.000090,0.636288,0.239369,NaN,0.300918,1.875
32,animals,vit_base_patch16_224,cls,layer_6,99.500,12.500000,-0.017135,0.489553,0.386103,NaN,0.287819,1.875
33,animals,vit_base_patch16_224,mean_tokens,layer_0,100.000,5.750000,-0.033336,0.329800,0.545856,NaN,0.197562,1.875
34,animals,vit_base_patch16_224,mean_tokens,layer_11,100.000,53.875000,0.015241,0.790175,0.085481,NaN,0.187760,1.875
36,animals,convnext_tiny,auto,layer_0,79.125,6.250000,-0.004605,0.339066,0.536591,NaN,0.175832,1.875
42,animals,vit_base_patch16_clip_224.openai,mean_tokens,layer_0,100.000,7.375000,-0.080863,0.344681,0.530975,NaN,0.168027,1.875
30,animals,vit_base_patch16_224,cls,layer_0,100.000,3.750000,-0.000174,0.273041,0.602616,NaN,0.143548,1.875
39,animals,vit_base_patch16_clip_224.openai,cls,layer_0,99.500,5.125000,-0.002436,0.288575,0.587081,NaN,0.142852,1.875
31,animals,vit_base_patch16_224,cls,layer_11,100.000,57.875000,0.008390,0.801563,0.074094,NaN,0.105265,1.875
41,animals,vit_base_patch16_clip_224.openai,cls,layer_6,15.750,3.500000,-0.040566,0.298937,0.576719,NaN,0.090579,1.875
38,animals,convnext_tiny,auto,layer_3,100.000,54.250000,0.036316,0.779050,0.096606,NaN,0.046470,1.875
10,fruits,vit_base_patch16_clip_224.openai,cls,layer_11,100.000,46.666667,-0.007951,0.691361,0.116093,63.333333,0.579635,1.250
13,fruits,vit_base_patch16_clip_224.openai,mean_tokens,layer_11,100.000,37.500000,-0.015778,0.630611,0.176843,48.333333,0.481256,1.250
14,fruits,vit_base_patch16_clip_224.openai,mean_tokens,layer_6,100.000,11.666667,-0.069563,0.445009,0.362444,18.333333,0.387395,1.250

## Corruption Sweep

These cells summarize the follow-up experiment that makes the identification task harder by corrupting the probe images more aggressively.

In [ ]:
CORRUPTION_OUTPUT_DIR = Path("results/vision/naturalistic_corruption")
corruption_summary_path = CORRUPTION_OUTPUT_DIR / "corruption_sweep_summary.json"
corruption_rows_path = CORRUPTION_OUTPUT_DIR / "corruption_sweep_rows.csv"
corruption_summary = json.loads(corruption_summary_path.read_text()) if corruption_summary_path.exists() else {}
corruption_rows = pd.read_csv(corruption_rows_path) if corruption_rows_path.exists() else pd.DataFrame()
corruption_summary

In [ ]:
# This table highlights the most useful non-ceiling identification regimes.
# Rows are grouped corruption settings that keep identification below saturation while still
# leaving the generalization task measurable.
if corruption_rows.empty:
    pd.DataFrame()
else:
    (corruption_rows
        .groupby(["category", "corruption_label", "model_name", "pooling", "layer"], as_index=False)
        .agg({
            "ident_accuracy": "mean",
            "gen_accuracy": "mean",
            "gen_avg_margin": "mean",
            "human_rdm_spearman": "mean",
        })
        .query("40 <= ident_accuracy <= 90")
        .sort_values(["category", "gen_accuracy"], ascending=[True, False])
        .head(30))

In [ ]:
# This cell lists the preview images saved for the corruption sweep.
# Each preview PNG shows clean vs corrupted probes side by side for one corruption regime.
sorted(str(path) for path in CORRUPTION_OUTPUT_DIR.glob("**/previews/*.png"))[:20]

## Corruption Spot Checks

These cells summarize the new identification-hardening spot checks that were added after the meeting concern about ceiling identification accuracy.

In [ ]:
SPOTCHECK_DIR = Path("results/vision/naturalistic_spotcheck")
spotcheck_summary_path = SPOTCHECK_DIR / "spotcheck_summary.csv"
spotcheck = pd.read_csv(spotcheck_summary_path) if spotcheck_summary_path.exists() else pd.DataFrame()
spotcheck

In [ ]:
# This table is the fastest way to explain the new result.
# Each row is one manually chosen corruption regime. The key columns are:
# - best_gen_ident_accuracy: identification accuracy on the strongest retrieval layer
# - best_gen_accuracy: generalization accuracy on that same retrieval-focused row
# - best_align_ident_accuracy: identification accuracy on the strongest alignment layer
# Main finding so far: strong occlusion plus optional decision noise can finally break the 100% identification ceiling.
spotcheck[[
    "category",
    "corruption_label",
    "decision_noise_std",
    "best_gen_layer",
    "best_gen_ident_accuracy",
    "best_gen_accuracy",
    "best_align_layer",
    "best_align_ident_accuracy",
    "best_align_accuracy",
]].sort_values(["category", "best_gen_ident_accuracy"]) if not spotcheck.empty else pd.DataFrame()

In [ ]:
sorted(str(path) for path in SPOTCHECK_DIR.glob("**/previews/*.png"))